#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InputActionWidget

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_InputActionWidget.BP_InputActionWidget_C
// 0x0000 (0x0430 - 0x0430)
class UBP_InputActionWidget_C final : public UCommonActionWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_InputActionWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_InputActionWidget_C")
	}
	static class UBP_InputActionWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_InputActionWidget_C>();
	}
};
DUMPER7_ASSERTS_UBP_InputActionWidget_C;

SDK_NAMESPACE_END
