#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TyrLobbyGameMode

#include "Basic.hpp"

#include "BP_TyrLobbyGameMode_classes.hpp"
#include "BP_TyrLobbyGameMode_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_TyrLobbyGameMode.BP_TyrLobbyGameMode_C.CheckAllPlayersReady
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_TyrLobbyGameMode_C::CheckAllPlayersReady()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrLobbyGameMode_C", "CheckAllPlayersReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TyrLobbyGameMode.BP_TyrLobbyGameMode_C.ExecuteUbergraph_BP_TyrLobbyGameMode
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TyrLobbyGameMode_C::ExecuteUbergraph_BP_TyrLobbyGameMode(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrLobbyGameMode_C", "ExecuteUbergraph_BP_TyrLobbyGameMode");

	Params::BP_TyrLobbyGameMode_C_ExecuteUbergraph_BP_TyrLobbyGameMode Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TyrLobbyGameMode.BP_TyrLobbyGameMode_C.K2_OnLogout
// (Event, Public, BlueprintEvent)
// Parameters:
// class AController*                      ExitingController                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_TyrLobbyGameMode_C::K2_OnLogout(class AController* ExitingController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrLobbyGameMode_C", "K2_OnLogout");

	Params::BP_TyrLobbyGameMode_C_K2_OnLogout Parms{};

	Parms.ExitingController = ExitingController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TyrLobbyGameMode.BP_TyrLobbyGameMode_C.K2_PostLogin
// (Event, Public, BlueprintEvent)
// Parameters:
// class APlayerController*                NewPlayer                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_TyrLobbyGameMode_C::K2_PostLogin(class APlayerController* NewPlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrLobbyGameMode_C", "K2_PostLogin");

	Params::BP_TyrLobbyGameMode_C_K2_PostLogin Parms{};

	Parms.NewPlayer = NewPlayer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TyrLobbyGameMode.BP_TyrLobbyGameMode_C.OnMessageReceived_FDFA8F0245B8C281A5D97BA9722D8FF5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAsyncAction_ListenForGameplayMessage*ProxyObject                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              ActualChannel                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void ABP_TyrLobbyGameMode_C::OnMessageReceived_FDFA8F0245B8C281A5D97BA9722D8FF5(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrLobbyGameMode_C", "OnMessageReceived_FDFA8F0245B8C281A5D97BA9722D8FF5");

	Params::BP_TyrLobbyGameMode_C_OnMessageReceived_FDFA8F0245B8C281A5D97BA9722D8FF5 Parms{};

	Parms.ProxyObject = ProxyObject;
	Parms.ActualChannel = std::move(ActualChannel);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TyrLobbyGameMode.BP_TyrLobbyGameMode_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_TyrLobbyGameMode_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrLobbyGameMode_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TyrLobbyGameMode.BP_TyrLobbyGameMode_C.StartGame
// (BlueprintCallable, BlueprintEvent)

void ABP_TyrLobbyGameMode_C::StartGame()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrLobbyGameMode_C", "StartGame");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
