#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TyrGameState

#include "Basic.hpp"

#include "BP_TyrGameState_classes.hpp"
#include "BP_TyrGameState_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_TyrGameState.BP_TyrGameState_C.BeginGame
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  InStartTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TyrGameState_C::BeginGame(double InStartTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrGameState_C", "BeginGame");

	Params::BP_TyrGameState_C_BeginGame Parms{};

	Parms.InStartTime = InStartTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TyrGameState.BP_TyrGameState_C.BeginPrematch
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  InTime                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TyrGameState_C::BeginPrematch(double InTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrGameState_C", "BeginPrematch");

	Params::BP_TyrGameState_C_BeginPrematch Parms{};

	Parms.InTime = InTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TyrGameState.BP_TyrGameState_C.Countdown
// (BlueprintCallable, BlueprintEvent)

void ABP_TyrGameState_C::Countdown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrGameState_C", "Countdown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TyrGameState.BP_TyrGameState_C.DestroyVehicles
// (BlueprintCallable, BlueprintEvent)

void ABP_TyrGameState_C::DestroyVehicles()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrGameState_C", "DestroyVehicles");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TyrGameState.BP_TyrGameState_C.ExecuteUbergraph_BP_TyrGameState
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TyrGameState_C::ExecuteUbergraph_BP_TyrGameState(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrGameState_C", "ExecuteUbergraph_BP_TyrGameState");

	Params::BP_TyrGameState_C_ExecuteUbergraph_BP_TyrGameState Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TyrGameState.BP_TyrGameState_C.MatchEnd
// (BlueprintCallable, BlueprintEvent)

void ABP_TyrGameState_C::MatchEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrGameState_C", "MatchEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TyrGameState.BP_TyrGameState_C.Multicast_SendEndGameStats
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FBP_EndGameStats&          InEndGameStats                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_TyrGameState_C::Multicast_SendEndGameStats(const struct FBP_EndGameStats& InEndGameStats)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrGameState_C", "Multicast_SendEndGameStats");

	Params::BP_TyrGameState_C_Multicast_SendEndGameStats Parms{};

	Parms.InEndGameStats = std::move(InEndGameStats);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TyrGameState.BP_TyrGameState_C.OnRep_MatchTime
// (BlueprintCallable, BlueprintEvent)

void ABP_TyrGameState_C::OnRep_MatchTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrGameState_C", "OnRep_MatchTime");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TyrGameState.BP_TyrGameState_C.OnRep_PubMatchGuid
// (HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_TyrGameState_C::OnRep_PubMatchGuid()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrGameState_C", "OnRep_PubMatchGuid");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TyrGameState.BP_TyrGameState_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_TyrGameState_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrGameState_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TyrGameState.BP_TyrGameState_C.UpdateCaptureProgress
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TeamId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CapturePoints                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TyrGameState_C::UpdateCaptureProgress(int32 TeamId, int32 CapturePoints)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrGameState_C", "UpdateCaptureProgress");

	Params::BP_TyrGameState_C_UpdateCaptureProgress Parms{};

	Parms.TeamId = TeamId;
	Parms.CapturePoints = CapturePoints;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TyrGameState.BP_TyrGameState_C.IsGameOver
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_TyrGameState_C::IsGameOver() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TyrGameState_C", "IsGameOver");

	Params::BP_TyrGameState_C_IsGameOver Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
