#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TestBotTank

#include "Basic.hpp"

#include "BP_TestBotTank_classes.hpp"
#include "BP_TestBotTank_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_TestBotTank.BP_TestBotTank_C.ApplyModuleDamage
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_TestBotTank_C::ApplyModuleDamage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TestBotTank_C", "ApplyModuleDamage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TestBotTank.BP_TestBotTank_C.ExecuteUbergraph_BP_TestBotTank
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TestBotTank_C::ExecuteUbergraph_BP_TestBotTank(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TestBotTank_C", "ExecuteUbergraph_BP_TestBotTank");

	Params::BP_TestBotTank_C_ExecuteUbergraph_BP_TestBotTank Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TestBotTank.BP_TestBotTank_C.OnUpdateThrottle
// (BlueprintCallable, BlueprintEvent)

void ABP_TestBotTank_C::OnUpdateThrottle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TestBotTank_C", "OnUpdateThrottle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TestBotTank.BP_TestBotTank_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_TestBotTank_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TestBotTank_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TestBotTank.BP_TestBotTank_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ABP_TestBotTank_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TestBotTank_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TestBotTank.BP_TestBotTank_C.ReceivePossess
// (Event, Protected, BlueprintEvent)
// Parameters:
// class APawn*                            PossessedPawn                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_TestBotTank_C::ReceivePossess(class APawn* PossessedPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TestBotTank_C", "ReceivePossess");

	Params::BP_TestBotTank_C_ReceivePossess Parms{};

	Parms.PossessedPawn = PossessedPawn;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
