#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_FirstSpotAssist

#include "Basic.hpp"

#include "BPC_FirstSpotAssist_classes.hpp"
#include "BPC_FirstSpotAssist_parameters.hpp"


SDK_NAMESPACE_START

// Function BPC_FirstSpotAssist.BPC_FirstSpotAssist_C.ExecuteUbergraph_BPC_FirstSpotAssist
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_FirstSpotAssist_C::ExecuteUbergraph_BPC_FirstSpotAssist(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_FirstSpotAssist_C", "ExecuteUbergraph_BPC_FirstSpotAssist");

	Params::BPC_FirstSpotAssist_C_ExecuteUbergraph_BPC_FirstSpotAssist Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_FirstSpotAssist.BPC_FirstSpotAssist_C.OnMessageReceived_7CA33BCEA74EF03753A83E86979B06C5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAsyncAction_ListenForGameplayMessage*ProxyObject                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              ActualChannel                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UBPC_FirstSpotAssist_C::OnMessageReceived_7CA33BCEA74EF03753A83E86979B06C5(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_FirstSpotAssist_C", "OnMessageReceived_7CA33BCEA74EF03753A83E86979B06C5");

	Params::BPC_FirstSpotAssist_C_OnMessageReceived_7CA33BCEA74EF03753A83E86979B06C5 Parms{};

	Parms.ProxyObject = ProxyObject;
	Parms.ActualChannel = std::move(ActualChannel);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_FirstSpotAssist.BPC_FirstSpotAssist_C.StartListening
// (Event, Public, BlueprintEvent)

void UBPC_FirstSpotAssist_C::StartListening()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_FirstSpotAssist_C", "StartListening");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_FirstSpotAssist.BPC_FirstSpotAssist_C.StopListening
// (Event, Public, BlueprintEvent)

void UBPC_FirstSpotAssist_C::StopListening()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_FirstSpotAssist_C", "StopListening");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
