#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_AutoFlipComponent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPC_AutoFlipComponent.BPC_AutoFlipComponent_C
// 0x0018 (0x00D0 - 0x00B8)
class UBPC_AutoFlipComponent_C final : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        IsFlippedAngleCutoff;                              // 0x00C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        IsFlippedVelocityCutoff;                           // 0x00C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BPC_AutoFlipComponent(int32 EntryPoint);
	void InitializeAbilitySystem(class UAbilitySystemComponent* AbilitySystem);
	void PostPlayerStateInitializeAbilitySystem(class UAbilitySystemComponent* AbilitySystem);
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPC_AutoFlipComponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPC_AutoFlipComponent_C")
	}
	static class UBPC_AutoFlipComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_AutoFlipComponent_C>();
	}
};
DUMPER7_ASSERTS_UBPC_AutoFlipComponent_C;

SDK_NAMESPACE_END
