#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPCN_CameraSwapLookEvaluator

#include "Basic.hpp"

#include "BPCN_CameraSwapLookEvaluator_classes.hpp"
#include "BPCN_CameraSwapLookEvaluator_parameters.hpp"


SDK_NAMESPACE_START

// Function BPCN_CameraSwapLookEvaluator.BPCN_CameraSwapLookEvaluator_C.InitializeCameraNode
// (Event, Public, BlueprintEvent)

void UBPCN_CameraSwapLookEvaluator_C::InitializeCameraNode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPCN_CameraSwapLookEvaluator_C", "InitializeCameraNode");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPCN_CameraSwapLookEvaluator.BPCN_CameraSwapLookEvaluator_C.OnSwapToSpectatorThirdPerson
// (BlueprintCallable, BlueprintEvent)

void UBPCN_CameraSwapLookEvaluator_C::OnSwapToSpectatorThirdPerson()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPCN_CameraSwapLookEvaluator_C", "OnSwapToSpectatorThirdPerson");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPCN_CameraSwapLookEvaluator.BPCN_CameraSwapLookEvaluator_C.TickCameraNode
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPCN_CameraSwapLookEvaluator_C::TickCameraNode(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPCN_CameraSwapLookEvaluator_C", "TickCameraNode");

	Params::BPCN_CameraSwapLookEvaluator_C_TickCameraNode Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPCN_CameraSwapLookEvaluator.BPCN_CameraSwapLookEvaluator_C.ExecuteUbergraph_BPCN_CameraSwapLookEvaluator
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPCN_CameraSwapLookEvaluator_C::ExecuteUbergraph_BPCN_CameraSwapLookEvaluator(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPCN_CameraSwapLookEvaluator_C", "ExecuteUbergraph_BPCN_CameraSwapLookEvaluator");

	Params::BPCN_CameraSwapLookEvaluator_C_ExecuteUbergraph_BPCN_CameraSwapLookEvaluator Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
