#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_environment_presets

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum E_environment_presets.E_environment_presets
// NumValues: 0x0003
enum class E_environment_presets : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	E_environment_MAX                        = 2,
};

SDK_NAMESPACE_END
