#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Blink

#include "Basic.hpp"

#include "GA_Blink_classes.hpp"
#include "GA_Blink_parameters.hpp"


SDK_NAMESPACE_START

// Function GA_Blink.GA_Blink_C.Client_PlayAnim
// (Net, NetClient, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_BaseTank_C*                   BlinkingVehicle                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_Blink_C::Client_PlayAnim(class ABP_BaseTank_C* BlinkingVehicle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Blink_C", "Client_PlayAnim");

	Params::GA_Blink_C_Client_PlayAnim Parms{};

	Parms.BlinkingVehicle = BlinkingVehicle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Blink.GA_Blink_C.ExecuteUbergraph_GA_Blink
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Blink_C::ExecuteUbergraph_GA_Blink(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Blink_C", "ExecuteUbergraph_GA_Blink");

	Params::GA_Blink_C_ExecuteUbergraph_GA_Blink Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Blink.GA_Blink_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Blink_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Blink_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Blink.GA_Blink_C.OnBlendedIn_40C51E484AA801B76C95FDBB37DC02A5
// (BlueprintCallable, BlueprintEvent)

void UGA_Blink_C::OnBlendedIn_40C51E484AA801B76C95FDBB37DC02A5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Blink_C", "OnBlendedIn_40C51E484AA801B76C95FDBB37DC02A5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Blink.GA_Blink_C.OnBlendOut_40C51E484AA801B76C95FDBB37DC02A5
// (BlueprintCallable, BlueprintEvent)

void UGA_Blink_C::OnBlendOut_40C51E484AA801B76C95FDBB37DC02A5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Blink_C", "OnBlendOut_40C51E484AA801B76C95FDBB37DC02A5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Blink.GA_Blink_C.OnBlendOut_434B7999483B55168CCAAB90F399E6BE
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Blink_C::OnBlendOut_434B7999483B55168CCAAB90F399E6BE(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Blink_C", "OnBlendOut_434B7999483B55168CCAAB90F399E6BE");

	Params::GA_Blink_C_OnBlendOut_434B7999483B55168CCAAB90F399E6BE Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Blink.GA_Blink_C.OnCancelled_40C51E484AA801B76C95FDBB37DC02A5
// (BlueprintCallable, BlueprintEvent)

void UGA_Blink_C::OnCancelled_40C51E484AA801B76C95FDBB37DC02A5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Blink_C", "OnCancelled_40C51E484AA801B76C95FDBB37DC02A5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Blink.GA_Blink_C.OnCompleted_40C51E484AA801B76C95FDBB37DC02A5
// (BlueprintCallable, BlueprintEvent)

void UGA_Blink_C::OnCompleted_40C51E484AA801B76C95FDBB37DC02A5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Blink_C", "OnCompleted_40C51E484AA801B76C95FDBB37DC02A5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Blink.GA_Blink_C.OnCompleted_434B7999483B55168CCAAB90F399E6BE
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Blink_C::OnCompleted_434B7999483B55168CCAAB90F399E6BE(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Blink_C", "OnCompleted_434B7999483B55168CCAAB90F399E6BE");

	Params::GA_Blink_C_OnCompleted_434B7999483B55168CCAAB90F399E6BE Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Blink.GA_Blink_C.OnInterrupted_40C51E484AA801B76C95FDBB37DC02A5
// (BlueprintCallable, BlueprintEvent)

void UGA_Blink_C::OnInterrupted_40C51E484AA801B76C95FDBB37DC02A5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Blink_C", "OnInterrupted_40C51E484AA801B76C95FDBB37DC02A5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Blink.GA_Blink_C.OnInterrupted_434B7999483B55168CCAAB90F399E6BE
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Blink_C::OnInterrupted_434B7999483B55168CCAAB90F399E6BE(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Blink_C", "OnInterrupted_434B7999483B55168CCAAB90F399E6BE");

	Params::GA_Blink_C_OnInterrupted_434B7999483B55168CCAAB90F399E6BE Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Blink.GA_Blink_C.OnNotifyBegin_40C51E484AA801B76C95FDBB37DC02A5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Blink_C::OnNotifyBegin_40C51E484AA801B76C95FDBB37DC02A5(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Blink_C", "OnNotifyBegin_40C51E484AA801B76C95FDBB37DC02A5");

	Params::GA_Blink_C_OnNotifyBegin_40C51E484AA801B76C95FDBB37DC02A5 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Blink.GA_Blink_C.OnNotifyBegin_434B7999483B55168CCAAB90F399E6BE
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Blink_C::OnNotifyBegin_434B7999483B55168CCAAB90F399E6BE(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Blink_C", "OnNotifyBegin_434B7999483B55168CCAAB90F399E6BE");

	Params::GA_Blink_C_OnNotifyBegin_434B7999483B55168CCAAB90F399E6BE Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Blink.GA_Blink_C.OnNotifyEnd_40C51E484AA801B76C95FDBB37DC02A5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Blink_C::OnNotifyEnd_40C51E484AA801B76C95FDBB37DC02A5(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Blink_C", "OnNotifyEnd_40C51E484AA801B76C95FDBB37DC02A5");

	Params::GA_Blink_C_OnNotifyEnd_40C51E484AA801B76C95FDBB37DC02A5 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Blink.GA_Blink_C.OnNotifyEnd_434B7999483B55168CCAAB90F399E6BE
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Blink_C::OnNotifyEnd_434B7999483B55168CCAAB90F399E6BE(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Blink_C", "OnNotifyEnd_434B7999483B55168CCAAB90F399E6BE");

	Params::GA_Blink_C_OnNotifyEnd_434B7999483B55168CCAAB90F399E6BE Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Blink.GA_Blink_C.OnStarted_40C51E484AA801B76C95FDBB37DC02A5
// (BlueprintCallable, BlueprintEvent)

void UGA_Blink_C::OnStarted_40C51E484AA801B76C95FDBB37DC02A5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Blink_C", "OnStarted_40C51E484AA801B76C95FDBB37DC02A5");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
