#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_AttachMissile_OnHit

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GC_AttachMissile_OnHit.GC_AttachMissile_OnHit_C
// 0x0010 (0x0328 - 0x0318)
class AGC_AttachMissile_OnHit_C final : public AGameplayCueNotify_Actor
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0318(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ATyrWheeledVehiclePawnBase*             CastingPawn;                                       // 0x0320(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	bool OnExecute(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GC_AttachMissile_OnHit_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GC_AttachMissile_OnHit_C")
	}
	static class AGC_AttachMissile_OnHit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_AttachMissile_OnHit_C>();
	}
};
DUMPER7_ASSERTS_AGC_AttachMissile_OnHit_C;

SDK_NAMESPACE_END
