#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_SentinelAiming

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GC_SentinelAiming.GC_SentinelAiming_C
// 0x0008 (0x0320 - 0x0318)
class AGC_SentinelAiming_C final : public AGameplayCueNotify_Actor
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0318(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	bool OnActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	bool OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GC_SentinelAiming_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GC_SentinelAiming_C")
	}
	static class AGC_SentinelAiming_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_SentinelAiming_C>();
	}
};
DUMPER7_ASSERTS_AGC_SentinelAiming_C;

SDK_NAMESPACE_END
