#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Map_Garage

#include "Basic.hpp"

#include "Map_Garage_classes.hpp"
#include "Map_Garage_parameters.hpp"


SDK_NAMESPACE_START

// Function Map_Garage.Map_Garage_C.ResetBackgroundAnimationTimer
// (BlueprintCallable, BlueprintEvent)

void AMap_Garage_C::ResetBackgroundAnimationTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Map_Garage_C", "ResetBackgroundAnimationTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Map_Garage.Map_Garage_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void AMap_Garage_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Map_Garage_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Map_Garage.Map_Garage_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AMap_Garage_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Map_Garage_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Map_Garage.Map_Garage_C.PlayRandomBackgroundAnimation
// (BlueprintCallable, BlueprintEvent)

void AMap_Garage_C::PlayRandomBackgroundAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Map_Garage_C", "PlayRandomBackgroundAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Map_Garage.Map_Garage_C.ExecuteUbergraph_Map_Garage
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMap_Garage_C::ExecuteUbergraph_Map_Garage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Map_Garage_C", "ExecuteUbergraph_Map_Garage");

	Params::Map_Garage_C_ExecuteUbergraph_Map_Garage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
