#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PropertyAnimator

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function PropertyAnimator.PropertyAnimatorCounter.GetAvailableFormatNames
// 0x0010 (0x0010 - 0x0000)
struct PropertyAnimatorCounter_GetAvailableFormatNames final
{
public:
	TArray<class FName>                           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PropertyAnimatorCounter_GetAvailableFormatNames;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
