#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VM_Cosmetics

#include "Basic.hpp"

#include "VM_Cosmetics_classes.hpp"
#include "VM_Cosmetics_parameters.hpp"


SDK_NAMESPACE_START

// Function VM_Cosmetics.VM_Cosmetics_C.ExecuteUbergraph_VM_Cosmetics
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UVM_Cosmetics_C::ExecuteUbergraph_VM_Cosmetics(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Cosmetics_C", "ExecuteUbergraph_VM_Cosmetics");

	Params::VM_Cosmetics_C_ExecuteUbergraph_VM_Cosmetics Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function VM_Cosmetics.VM_Cosmetics_C.GetOrCreateVehicleCosmetics
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              InVehicleTag                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// class UVM_Cosmetics_Vehicle_C**         CosmeticsVehicleViewModel                              (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UVM_Cosmetics_C::GetOrCreateVehicleCosmetics(const struct FGameplayTag& InVehicleTag, class UVM_Cosmetics_Vehicle_C** CosmeticsVehicleViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Cosmetics_C", "GetOrCreateVehicleCosmetics");

	Params::VM_Cosmetics_C_GetOrCreateVehicleCosmetics Parms{};

	Parms.InVehicleTag = std::move(InVehicleTag);

	UObject::ProcessEvent(Func, &Parms);

	if (CosmeticsVehicleViewModel != nullptr)
		*CosmeticsVehicleViewModel = Parms.CosmeticsVehicleViewModel;
}


// Function VM_Cosmetics.VM_Cosmetics_C.InitializeCosmetics
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UVM_Cosmetics_C::InitializeCosmetics()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Cosmetics_C", "InitializeCosmetics");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VM_Cosmetics.VM_Cosmetics_C.OnCosmeticsUserDataUpdated
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FTyrCosmeticsMessage&      Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UVM_Cosmetics_C::OnCosmeticsUserDataUpdated(const struct FTyrCosmeticsMessage& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Cosmetics_C", "OnCosmeticsUserDataUpdated");

	Params::VM_Cosmetics_C_OnCosmeticsUserDataUpdated Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function VM_Cosmetics.VM_Cosmetics_C.OnInitialPlayerReady
// (Event, Protected, BlueprintEvent)

void UVM_Cosmetics_C::OnInitialPlayerReady()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Cosmetics_C", "OnInitialPlayerReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VM_Cosmetics.VM_Cosmetics_C.OnInventoryItemAdded
// (BlueprintCallable, BlueprintEvent)

void UVM_Cosmetics_C::OnInventoryItemAdded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Cosmetics_C", "OnInventoryItemAdded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VM_Cosmetics.VM_Cosmetics_C.OnMessageReceived_665ED7634C0087626A67788E86E1CE86
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAsyncAction_ListenForGameplayMessage*ProxyObject                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              ActualChannel                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UVM_Cosmetics_C::OnMessageReceived_665ED7634C0087626A67788E86E1CE86(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Cosmetics_C", "OnMessageReceived_665ED7634C0087626A67788E86E1CE86");

	Params::VM_Cosmetics_C_OnMessageReceived_665ED7634C0087626A67788E86E1CE86 Parms{};

	Parms.ProxyObject = ProxyObject;
	Parms.ActualChannel = std::move(ActualChannel);

	UObject::ProcessEvent(Func, &Parms);
}


// Function VM_Cosmetics.VM_Cosmetics_C.OnMessageReceived_C5A0B0D44AA7D6EC648E12BA22E8B74C
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAsyncAction_ListenForGameplayMessage*ProxyObject                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              ActualChannel                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UVM_Cosmetics_C::OnMessageReceived_C5A0B0D44AA7D6EC648E12BA22E8B74C(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Cosmetics_C", "OnMessageReceived_C5A0B0D44AA7D6EC648E12BA22E8B74C");

	Params::VM_Cosmetics_C_OnMessageReceived_C5A0B0D44AA7D6EC648E12BA22E8B74C Parms{};

	Parms.ProxyObject = ProxyObject;
	Parms.ActualChannel = std::move(ActualChannel);

	UObject::ProcessEvent(Func, &Parms);
}


// Function VM_Cosmetics.VM_Cosmetics_C.GetVehicleCosmetics
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// const struct FGameplayTag&              InVehicleTag                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// class UVM_Cosmetics_Vehicle_C**         VehicleCosmetics_0                                     (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UVM_Cosmetics_C::GetVehicleCosmetics(const struct FGameplayTag& InVehicleTag, class UVM_Cosmetics_Vehicle_C** VehicleCosmetics_0) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Cosmetics_C", "GetVehicleCosmetics");

	Params::VM_Cosmetics_C_GetVehicleCosmetics Parms{};

	Parms.InVehicleTag = std::move(InVehicleTag);

	UObject::ProcessEvent(Func, &Parms);

	if (VehicleCosmetics_0 != nullptr)
		*VehicleCosmetics_0 = Parms.VehicleCosmetics_0;
}


SDK_NAMESPACE_END
