#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VM_Lobby_Map

#include "Basic.hpp"

#include "Tyr_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function VM_Lobby_Map.VM_Lobby_Map_C.InitializeFromMapInfo
// 0x00A8 (0x00A8 - 0x0000)
struct VM_Lobby_Map_C_InitializeFromMapInfo final
{
public:
	class FName                                   InMapName;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTyrMapInfoDataTableStruct             InMapInfo;                                         // 0x0008(0x0098)(BlueprintVisible, BlueprintReadOnly, Parm)
	bool                                          CallFunc_SetPropertyValueAndBroadcast_ReturnValue; // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetPropertyValueAndBroadcast_ReturnValue_1; // 0x00A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_VM_Lobby_Map_C_InitializeFromMapInfo;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
