#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VM_Leaderboard_Player

#include "Basic.hpp"

#include "VM_Leaderboard_Player_classes.hpp"
#include "VM_Leaderboard_Player_parameters.hpp"


SDK_NAMESPACE_START

// Function VM_Leaderboard_Player.VM_Leaderboard_Player_C.GetScoreValue
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UVM_Leaderboard_Player_C::GetScoreValue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Leaderboard_Player_C", "GetScoreValue");

	Params::VM_Leaderboard_Player_C_GetScoreValue Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VM_Leaderboard_Player.VM_Leaderboard_Player_C.RefreshPlayerProfile
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   bDidRefreshFromData                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UVM_Leaderboard_Player_C::RefreshPlayerProfile(bool* bDidRefreshFromData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Leaderboard_Player_C", "RefreshPlayerProfile");

	Params::VM_Leaderboard_Player_C_RefreshPlayerProfile Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bDidRefreshFromData != nullptr)
		*bDidRefreshFromData = Parms.bDidRefreshFromData;
}


// Function VM_Leaderboard_Player.VM_Leaderboard_Player_C.SetUserId
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    InUserId                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UVM_Leaderboard_Player_C::SetUserId(const class FString& InUserId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Leaderboard_Player_C", "SetUserId");

	Params::VM_Leaderboard_Player_C_SetUserId Parms{};

	Parms.InUserId = std::move(InUserId);

	UObject::ProcessEvent(Func, &Parms);
}


// Function VM_Leaderboard_Player.VM_Leaderboard_Player_C.UpdateFromLeaderboardScore
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FLeaderboardScore&         InScore                                                (BlueprintVisible, BlueprintReadOnly, Parm)
// TArray<struct FTyrLeaderboardTierThreshold>&InTierThreholds                                        (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UVM_Leaderboard_Player_C::UpdateFromLeaderboardScore(const struct FLeaderboardScore& InScore, TArray<struct FTyrLeaderboardTierThreshold>& InTierThreholds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Leaderboard_Player_C", "UpdateFromLeaderboardScore");

	Params::VM_Leaderboard_Player_C_UpdateFromLeaderboardScore Parms{};

	Parms.InScore = std::move(InScore);
	Parms.InTierThreholds = std::move(InTierThreholds);

	UObject::ProcessEvent(Func, &Parms);

	InTierThreholds = std::move(Parms.InTierThreholds);
}


// Function VM_Leaderboard_Player.VM_Leaderboard_Player_C.GetLocalPlayerTextColor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FSlateColor*                     SlateColor                                             (Parm, OutParm)

void UVM_Leaderboard_Player_C::GetLocalPlayerTextColor(struct FSlateColor* SlateColor) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Leaderboard_Player_C", "GetLocalPlayerTextColor");

	Params::VM_Leaderboard_Player_C_GetLocalPlayerTextColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SlateColor != nullptr)
		*SlateColor = std::move(Parms.SlateColor);
}


// Function VM_Leaderboard_Player.VM_Leaderboard_Player_C.GetRankIconFromScore
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// TSoftObjectPtr<class UMaterialInstance>*RankIcon_0                                             (Parm, OutParm, HasGetValueTypeHash)

void UVM_Leaderboard_Player_C::GetRankIconFromScore(TSoftObjectPtr<class UMaterialInstance>* RankIcon_0) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Leaderboard_Player_C", "GetRankIconFromScore");

	Params::VM_Leaderboard_Player_C_GetRankIconFromScore Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (RankIcon_0 != nullptr)
		*RankIcon_0 = Parms.RankIcon_0;
}


// Function VM_Leaderboard_Player.VM_Leaderboard_Player_C.GetRankText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UVM_Leaderboard_Player_C::GetRankText() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Leaderboard_Player_C", "GetRankText");

	Params::VM_Leaderboard_Player_C_GetRankText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VM_Leaderboard_Player.VM_Leaderboard_Player_C.GetRowBackerColor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UVM_Leaderboard_Player_C::GetRowBackerColor() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Leaderboard_Player_C", "GetRowBackerColor");

	Params::VM_Leaderboard_Player_C_GetRowBackerColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VM_Leaderboard_Player.VM_Leaderboard_Player_C.GetScoreText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UVM_Leaderboard_Player_C::GetScoreText() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Leaderboard_Player_C", "GetScoreText");

	Params::VM_Leaderboard_Player_C_GetScoreText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
