#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VM_Lobby_Connecting

#include "Basic.hpp"

#include "VM_Lobby_Connecting_classes.hpp"
#include "VM_Lobby_Connecting_parameters.hpp"


SDK_NAMESPACE_START

// Function VM_Lobby_Connecting.VM_Lobby_Connecting_C.ExecuteUbergraph_VM_Lobby_Connecting
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UVM_Lobby_Connecting_C::ExecuteUbergraph_VM_Lobby_Connecting(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Lobby_Connecting_C", "ExecuteUbergraph_VM_Lobby_Connecting");

	Params::VM_Lobby_Connecting_C_ExecuteUbergraph_VM_Lobby_Connecting Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function VM_Lobby_Connecting.VM_Lobby_Connecting_C.OnDeinitialized
// (Event, Protected, BlueprintEvent)

void UVM_Lobby_Connecting_C::OnDeinitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Lobby_Connecting_C", "OnDeinitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VM_Lobby_Connecting.VM_Lobby_Connecting_C.OnInitializedForGameState
// (Event, Protected, BlueprintEvent)

void UVM_Lobby_Connecting_C::OnInitializedForGameState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Lobby_Connecting_C", "OnInitializedForGameState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VM_Lobby_Connecting.VM_Lobby_Connecting_C.OnMessageReceived_3C41EC9747BD11CE0A3BB9A7982D34FE
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAsyncAction_ListenForGameplayMessage*ProxyObject                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              ActualChannel                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UVM_Lobby_Connecting_C::OnMessageReceived_3C41EC9747BD11CE0A3BB9A7982D34FE(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Lobby_Connecting_C", "OnMessageReceived_3C41EC9747BD11CE0A3BB9A7982D34FE");

	Params::VM_Lobby_Connecting_C_OnMessageReceived_3C41EC9747BD11CE0A3BB9A7982D34FE Parms{};

	Parms.ProxyObject = ProxyObject;
	Parms.ActualChannel = std::move(ActualChannel);

	UObject::ProcessEvent(Func, &Parms);
}


// Function VM_Lobby_Connecting.VM_Lobby_Connecting_C.OnMessageReceived_6E9544384EAF949F72CED1A6CCE712DA
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAsyncAction_ListenForGameplayMessage*ProxyObject                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              ActualChannel                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UVM_Lobby_Connecting_C::OnMessageReceived_6E9544384EAF949F72CED1A6CCE712DA(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Lobby_Connecting_C", "OnMessageReceived_6E9544384EAF949F72CED1A6CCE712DA");

	Params::VM_Lobby_Connecting_C_OnMessageReceived_6E9544384EAF949F72CED1A6CCE712DA Parms{};

	Parms.ProxyObject = ProxyObject;
	Parms.ActualChannel = std::move(ActualChannel);

	UObject::ProcessEvent(Func, &Parms);
}


// Function VM_Lobby_Connecting.VM_Lobby_Connecting_C.OnMessageReceived_B16C7A824B676860821FD38AE76AFCA1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAsyncAction_ListenForGameplayMessage*ProxyObject                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              ActualChannel                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UVM_Lobby_Connecting_C::OnMessageReceived_B16C7A824B676860821FD38AE76AFCA1(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Lobby_Connecting_C", "OnMessageReceived_B16C7A824B676860821FD38AE76AFCA1");

	Params::VM_Lobby_Connecting_C_OnMessageReceived_B16C7A824B676860821FD38AE76AFCA1 Parms{};

	Parms.ProxyObject = ProxyObject;
	Parms.ActualChannel = std::move(ActualChannel);

	UObject::ProcessEvent(Func, &Parms);
}


// Function VM_Lobby_Connecting.VM_Lobby_Connecting_C.OnMessageReceived_EB0DE8534B8F10DEA9286C9189898055
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAsyncAction_ListenForGameplayMessage*ProxyObject                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              ActualChannel                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UVM_Lobby_Connecting_C::OnMessageReceived_EB0DE8534B8F10DEA9286C9189898055(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Lobby_Connecting_C", "OnMessageReceived_EB0DE8534B8F10DEA9286C9189898055");

	Params::VM_Lobby_Connecting_C_OnMessageReceived_EB0DE8534B8F10DEA9286C9189898055 Parms{};

	Parms.ProxyObject = ProxyObject;
	Parms.ActualChannel = std::move(ActualChannel);

	UObject::ProcessEvent(Func, &Parms);
}


// Function VM_Lobby_Connecting.VM_Lobby_Connecting_C.UpdateCanShowConnectingPlayerCount
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UVM_Lobby_Connecting_C::UpdateCanShowConnectingPlayerCount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Lobby_Connecting_C", "UpdateCanShowConnectingPlayerCount");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VM_Lobby_Connecting.VM_Lobby_Connecting_C.UpdateNumConnectedPlayers
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UVM_Lobby_Connecting_C::UpdateNumConnectedPlayers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Lobby_Connecting_C", "UpdateNumConnectedPlayers");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VM_Lobby_Connecting.VM_Lobby_Connecting_C.UpdateNumExpectedPlayers
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UVM_Lobby_Connecting_C::UpdateNumExpectedPlayers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Lobby_Connecting_C", "UpdateNumExpectedPlayers");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VM_Lobby_Connecting.VM_Lobby_Connecting_C.GetConnectedPlayersPercent
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UVM_Lobby_Connecting_C::GetConnectedPlayersPercent() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Lobby_Connecting_C", "GetConnectedPlayersPercent");

	Params::VM_Lobby_Connecting_C_GetConnectedPlayersPercent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VM_Lobby_Connecting.VM_Lobby_Connecting_C.GetConnectPlayersAnimatedFromPercent
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// double                                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

double UVM_Lobby_Connecting_C::GetConnectPlayersAnimatedFromPercent() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Lobby_Connecting_C", "GetConnectPlayersAnimatedFromPercent");

	Params::VM_Lobby_Connecting_C_GetConnectPlayersAnimatedFromPercent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VM_Lobby_Connecting.VM_Lobby_Connecting_C.GetNumConnectedPlayersText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UVM_Lobby_Connecting_C::GetNumConnectedPlayersText() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Lobby_Connecting_C", "GetNumConnectedPlayersText");

	Params::VM_Lobby_Connecting_C_GetNumConnectedPlayersText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VM_Lobby_Connecting.VM_Lobby_Connecting_C.GetNumExpectedPlayersText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UVM_Lobby_Connecting_C::GetNumExpectedPlayersText() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Lobby_Connecting_C", "GetNumExpectedPlayersText");

	Params::VM_Lobby_Connecting_C_GetNumExpectedPlayersText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
