#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VM_MediaControls

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Tyr_structs.hpp"
#include "Tyr_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass VM_MediaControls.VM_MediaControls_C
// 0x0008 (0x0088 - 0x0080)
class UVM_MediaControls_C final : public UTyrMediaControlsViewModel
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0080(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_VM_MediaControls(int32 EntryPoint);
	void OnPlaybackStateChanged_BP(ETyrMediaControlPlaybackState InPlaybackState);
	void OnTimeChanged_BP(const struct FTimespan& CurrentTime, const struct FTimespan& Duration);

	void GetPercentComplete(double* Percent) const;
	void GetPlaybackStateBrush(struct FSlateBrush* NewParam) const;
	void GetTimeText(class FText* Time) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("VM_MediaControls_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VM_MediaControls_C")
	}
	static class UVM_MediaControls_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVM_MediaControls_C>();
	}
};
DUMPER7_ASSERTS_UVM_MediaControls_C;

SDK_NAMESPACE_END
