#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VM_Vehicle_Level

#include "Basic.hpp"

#include "VM_Vehicle_Level_classes.hpp"
#include "VM_Vehicle_Level_parameters.hpp"


SDK_NAMESPACE_START

// Function VM_Vehicle_Level.VM_Vehicle_Level_C.ApplyGainedProgress
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InGainedXP                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UVM_Vehicle_Level_C::ApplyGainedProgress(int32 InGainedXP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Vehicle_Level_C", "ApplyGainedProgress");

	Params::VM_Vehicle_Level_C_ApplyGainedProgress Parms{};

	Parms.InGainedXP = InGainedXP;

	UObject::ProcessEvent(Func, &Parms);
}


// Function VM_Vehicle_Level.VM_Vehicle_Level_C.GainedProgressApplied
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UVM_Vehicle_Level_C::GainedProgressApplied()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Vehicle_Level_C", "GainedProgressApplied");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VM_Vehicle_Level.VM_Vehicle_Level_C.GetOrCreateItemReward
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              InItemTag                                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// class UVM_Vehicle_Level_Reward_C**      RewardViewModel                                        (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UVM_Vehicle_Level_C::GetOrCreateItemReward(const struct FGameplayTag& InItemTag, class UVM_Vehicle_Level_Reward_C** RewardViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Vehicle_Level_C", "GetOrCreateItemReward");

	Params::VM_Vehicle_Level_C_GetOrCreateItemReward Parms{};

	Parms.InItemTag = std::move(InItemTag);

	UObject::ProcessEvent(Func, &Parms);

	if (RewardViewModel != nullptr)
		*RewardViewModel = Parms.RewardViewModel;
}


// Function VM_Vehicle_Level.VM_Vehicle_Level_C.SetLevel
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InLevelIndex                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UVM_Vehicle_Level_C::SetLevel(int32 InLevelIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Vehicle_Level_C", "SetLevel");

	Params::VM_Vehicle_Level_C_SetLevel Parms{};

	Parms.InLevelIndex = InLevelIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function VM_Vehicle_Level.VM_Vehicle_Level_C.UpdateFromProgressionData
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bInIsCurrentLevel                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bInIsComplete                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InCurrentXP                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InRequiredXP                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UVM_Vehicle_Level_C::UpdateFromProgressionData(bool bInIsCurrentLevel, bool bInIsComplete, int32 InCurrentXP, int32 InRequiredXP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Vehicle_Level_C", "UpdateFromProgressionData");

	Params::VM_Vehicle_Level_C_UpdateFromProgressionData Parms{};

	Parms.bInIsCurrentLevel = bInIsCurrentLevel;
	Parms.bInIsComplete = bInIsComplete;
	Parms.InCurrentXP = InCurrentXP;
	Parms.InRequiredXP = InRequiredXP;

	UObject::ProcessEvent(Func, &Parms);
}


// Function VM_Vehicle_Level.VM_Vehicle_Level_C.UpdateHeadlineReward
// (Public, BlueprintCallable, BlueprintEvent)

void UVM_Vehicle_Level_C::UpdateHeadlineReward()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Vehicle_Level_C", "UpdateHeadlineReward");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VM_Vehicle_Level.VM_Vehicle_Level_C.UpdateRepeatableReward
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// TSoftObjectPtr<class UTexture2D>        InIcon                                                 (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// const class FText&                      InTitle                                                (BlueprintVisible, BlueprintReadOnly, Parm)
// const class FText&                      InDescription                                          (BlueprintVisible, BlueprintReadOnly, Parm)

void UVM_Vehicle_Level_C::UpdateRepeatableReward(TSoftObjectPtr<class UTexture2D> InIcon, const class FText& InTitle, const class FText& InDescription)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Vehicle_Level_C", "UpdateRepeatableReward");

	Params::VM_Vehicle_Level_C_UpdateRepeatableReward Parms{};

	Parms.InIcon = InIcon;
	Parms.InTitle = std::move(InTitle);
	Parms.InDescription = std::move(InDescription);

	UObject::ProcessEvent(Func, &Parms);
}


// Function VM_Vehicle_Level.VM_Vehicle_Level_C.UpdateRequiredXP
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InRequiredXP                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UVM_Vehicle_Level_C::UpdateRequiredXP(int32 InRequiredXP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Vehicle_Level_C", "UpdateRequiredXP");

	Params::VM_Vehicle_Level_C_UpdateRequiredXP Parms{};

	Parms.InRequiredXP = InRequiredXP;

	UObject::ProcessEvent(Func, &Parms);
}


// Function VM_Vehicle_Level.VM_Vehicle_Level_C.UpdateRewardItem
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FTrackableRewardBlob&      InRewardBlob                                           (BlueprintVisible, BlueprintReadOnly, Parm)
// const struct FGameplayTag&              InVehicleTag                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UVM_Vehicle_Level_C::UpdateRewardItem(const struct FTrackableRewardBlob& InRewardBlob, const struct FGameplayTag& InVehicleTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Vehicle_Level_C", "UpdateRewardItem");

	Params::VM_Vehicle_Level_C_UpdateRewardItem Parms{};

	Parms.InRewardBlob = std::move(InRewardBlob);
	Parms.InVehicleTag = std::move(InVehicleTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function VM_Vehicle_Level.VM_Vehicle_Level_C.GetCurrentXP
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UVM_Vehicle_Level_C::GetCurrentXP() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Vehicle_Level_C", "GetCurrentXP");

	Params::VM_Vehicle_Level_C_GetCurrentXP Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VM_Vehicle_Level.VM_Vehicle_Level_C.GetGainedLevelProgress
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// double                                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

double UVM_Vehicle_Level_C::GetGainedLevelProgress() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Vehicle_Level_C", "GetGainedLevelProgress");

	Params::VM_Vehicle_Level_C_GetGainedLevelProgress Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VM_Vehicle_Level.VM_Vehicle_Level_C.GetLevelColor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FSlateColor                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateColor UVM_Vehicle_Level_C::GetLevelColor() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Vehicle_Level_C", "GetLevelColor");

	Params::VM_Vehicle_Level_C_GetLevelColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VM_Vehicle_Level.VM_Vehicle_Level_C.GetLevelProgress
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// double                                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

double UVM_Vehicle_Level_C::GetLevelProgress() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Vehicle_Level_C", "GetLevelProgress");

	Params::VM_Vehicle_Level_C_GetLevelProgress Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VM_Vehicle_Level.VM_Vehicle_Level_C.GetLevelProgressBar
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// int32*                                  NewParam                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UVM_Vehicle_Level_C::GetLevelProgressBar(int32* NewParam) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Vehicle_Level_C", "GetLevelProgressBar");

	Params::VM_Vehicle_Level_C_GetLevelProgressBar Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = Parms.NewParam;
}


// Function VM_Vehicle_Level.VM_Vehicle_Level_C.GetLevelProgressText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UVM_Vehicle_Level_C::GetLevelProgressText() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Vehicle_Level_C", "GetLevelProgressText");

	Params::VM_Vehicle_Level_C_GetLevelProgressText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VM_Vehicle_Level.VM_Vehicle_Level_C.GetLevelText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UVM_Vehicle_Level_C::GetLevelText() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Vehicle_Level_C", "GetLevelText");

	Params::VM_Vehicle_Level_C_GetLevelText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VM_Vehicle_Level.VM_Vehicle_Level_C.GetTargetLevelText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UVM_Vehicle_Level_C::GetTargetLevelText() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VM_Vehicle_Level_C", "GetTargetLevelText");

	Params::VM_Vehicle_Level_C_GetTargetLevelText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
