#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Loadout_Ammunition

#include "Basic.hpp"

#include "FieldNotification_structs.hpp"
#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.BndEvt__WBP_Loadout_Ammunition_Ammunition_TileView_K2Node_ComponentBoundEvent_0_OnItemIsHoveredChangedDynamic__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_Loadout_Ammunition_C_BndEvt__WBP_Loadout_Ammunition_Ammunition_TileView_K2Node_ComponentBoundEvent_0_OnItemIsHoveredChangedDynamic__DelegateSignature final
{
public:
	class UObject*                                Item;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsHovered;                                        // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_BndEvt__WBP_Loadout_Ammunition_Ammunition_TileView_K2Node_ComponentBoundEvent_0_OnItemIsHoveredChangedDynamic__DelegateSignature;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.BndEvt__WBP_Loadout_Ammunition_Ammunition_TileView_K2Node_ComponentBoundEvent_1_SimpleListItemEventDynamic__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_Loadout_Ammunition_C_BndEvt__WBP_Loadout_Ammunition_Ammunition_TileView_K2Node_ComponentBoundEvent_1_SimpleListItemEventDynamic__DelegateSignature final
{
public:
	class UObject*                                Item;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_BndEvt__WBP_Loadout_Ammunition_Ammunition_TileView_K2Node_ComponentBoundEvent_1_SimpleListItemEventDynamic__DelegateSignature;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.BndEvt__WBP_Loadout_Ammunition_Ammunition_TileView_K2Node_ComponentBoundEvent_3_OnListEntriesGeneratedDynamic__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct WBP_Loadout_Ammunition_C_BndEvt__WBP_Loadout_Ammunition_Ammunition_TileView_K2Node_ComponentBoundEvent_3_OnListEntriesGeneratedDynamic__DelegateSignature final
{
public:
	int32                                         NumEntries;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_BndEvt__WBP_Loadout_Ammunition_Ammunition_TileView_K2Node_ComponentBoundEvent_3_OnListEntriesGeneratedDynamic__DelegateSignature;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.ClearErrorMessage
// 0x0001 (0x0001 - 0x0000)
struct WBP_Loadout_Ammunition_C_ClearErrorMessage final
{
public:
	bool                                          CallFunc_SetPropertyValueAndBroadcast_ReturnValue; // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_ClearErrorMessage;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.DisplayErrorMessage
// 0x0018 (0x0018 - 0x0000)
struct WBP_Loadout_Ammunition_C_DisplayErrorMessage final
{
public:
	class FText                                   InErrorMessage;                                    // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
	bool                                          CallFunc_SetPropertyValueAndBroadcast_ReturnValue; // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_DisplayErrorMessage;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.ExecuteUbergraph_WBP_Loadout_Ammunition
// 0x02E0 (0x02E0 - 0x0000)
struct WBP_Loadout_Ammunition_C_ExecuteUbergraph_WBP_Loadout_Ammunition final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId;             // 0x0004(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_1;           // 0x000C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_2;           // 0x0014(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_3;           // 0x001C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_4;           // 0x0024(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_5;           // 0x002C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_6;           // 0x0034(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_7;           // 0x003C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_8;           // 0x0044(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_9;           // 0x004C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_10;          // 0x0054(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_11;          // 0x005C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_12;          // 0x0064(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_13;          // 0x006C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_14;          // 0x0074(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_15;          // 0x007C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_16;          // 0x0084(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_17;          // 0x008C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_18;          // 0x0094(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_19;          // 0x009C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_20;          // 0x00A4(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_21;          // 0x00AC(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_22;          // 0x00B4(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_23;          // 0x00BC(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_24;          // 0x00C4(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_25;          // 0x00CC(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_26;          // 0x00D4(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_27;          // 0x00DC(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_28;          // 0x00E4(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_29;          // 0x00EC(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_30;          // 0x00F4(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_31;          // 0x00FC(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_32;          // 0x0104(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_33;          // 0x010C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_34;          // 0x0114(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_35;          // 0x011C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_36;          // 0x0124(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_37;          // 0x012C(0x0008)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_134[0x4];                                      // 0x0134(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFieldNotificationId>           K2Node_MakeArray_Array;                            // 0x0138(0x0010)(ReferenceParm)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_38;          // 0x0148(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetPropertyValueAndBroadcastFields_ReturnValue; // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_151[0x3];                                      // 0x0151(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_39;          // 0x0154(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_40;          // 0x015C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_41;          // 0x0164(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_42;          // 0x016C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_43;          // 0x0174(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_44;          // 0x017C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_45;          // 0x0184(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_46;          // 0x018C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_47;          // 0x0194(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_48;          // 0x019C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_49;          // 0x01A4(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_50;          // 0x01AC(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_51;          // 0x01B4(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_52;          // 0x01BC(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_53;          // 0x01C4(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_54;          // 0x01CC(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_55;          // 0x01D4(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_56;          // 0x01DC(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_57;          // 0x01E4(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_58;          // 0x01EC(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_59;          // 0x01F4(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_60;          // 0x01FC(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_61;          // 0x0204(0x0008)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_20C[0x4];                                      // 0x020C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFieldNotificationId>           K2Node_MakeArray_Array_1;                          // 0x0210(0x0010)(ReferenceParm)
	class UObject*                                K2Node_ComponentBoundEvent_Item_1;                 // 0x0220(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsHovered;             // 0x0228(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_229[0x7];                                      // 0x0229(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_ComponentBoundEvent_Item;                   // 0x0230(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UVM_Ammunition_Shell_C*                 K2Node_DynamicCast_AsVM_Ammunition_Shell;          // 0x0238(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0240(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_241[0x7];                                      // 0x0241(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UVM_Ammunition_Shell_C*                 K2Node_DynamicCast_AsVM_Ammunition_Shell_1;        // 0x0248(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0250(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_251[0x3];                                      // 0x0251(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_62;          // 0x0254(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_63;          // 0x025C(0x0008)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_264[0x4];                                      // 0x0264(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UVM_Ammunition_Shell_C*                 K2Node_CustomEvent_ShellViewModel;                 // 0x0268(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_bShouldShowDetails;             // 0x0270(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_271[0x3];                                      // 0x0271(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_64;          // 0x0274(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_65;          // 0x027C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_66;          // 0x0284(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_67;          // 0x028C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_68;          // 0x0294(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_69;          // 0x029C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_70;          // 0x02A4(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFieldNotificationId                   K2Node_MakeStruct_FieldNotificationId_71;          // 0x02AC(0x0008)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B4[0x4];                                      // 0x02B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFieldNotificationId>           K2Node_MakeArray_Array_2;                          // 0x02B8(0x0010)(ReferenceParm)
	bool                                          CallFunc_SetPropertyValueAndBroadcastFields_ReturnValue_1; // 0x02C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasEquippedSlotShell_ReturnValue;         // 0x02C9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2CA[0x6];                                      // 0x02CA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UVM_Ammunition_Shell_C*                 CallFunc_GetEquippedSlotShell_ReturnValue;         // 0x02D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_NumEntries;             // 0x02D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetPropertyValueAndBroadcastFields_ReturnValue_2; // 0x02DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_ExecuteUbergraph_WBP_Loadout_Ammunition;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.OnShowAmmoDetailsChanged
// 0x0010 (0x0010 - 0x0000)
struct WBP_Loadout_Ammunition_C_OnShowAmmoDetailsChanged final
{
public:
	class UVM_Ammunition_Shell_C*                 ShellViewModel;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          bShouldShowDetails;                                // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_OnShowAmmoDetailsChanged;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.TryAutoFocus
// 0x0068 (0x0068 - 0x0000)
struct WBP_Loadout_Ammunition_C_TryAutoFocus final
{
public:
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UVM_Ammunition_Shell_C*                 CallFunc_GetEquippedSlotShell_ReturnValue;         // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class UUserWidget*>                    CallFunc_GetDisplayedEntryWidgets_ReturnValue;     // 0x0020(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_Array_Get_Item;                           // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_Loadout_Ammunition_Shell_C*        K2Node_DynamicCast_AsWBP_Loadout_Ammunition_Shell; // 0x0048(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_52[0x6];                                       // 0x0052(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_Array_Get_Item_1;                         // 0x0058(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_TryAutoFocus;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.__97a991f3-4760-2d1c-fbbd-3c9a37d6b32a_SourceToDest
// 0x0003 (0x0003 - 0x0000)
struct WBP_Loadout_Ammunition_C___97a991f3_4760_2d1c_fbbd_3c9a37d6b32a_SourceToDest final
{
public:
	ESlateVisibility                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasSelectedShell_ReturnValue;             // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              CallFunc_Conv_BoolToSlateVisibility_ReturnValue;   // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C___97a991f3_4760_2d1c_fbbd_3c9a37d6b32a_SourceToDest;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Convert Modifier to Percent Text
// 0x0100 (0x0100 - 0x0000)
struct WBP_Loadout_Ammunition_C_Convert_Modifier_to_Percent_Text final
{
public:
	double                                        InModifier;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   Result;                                            // 0x0008(0x0010)(Parm, OutParm)
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_DoubleToText_ReturnValue;            // 0x0028(0x0010)()
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0040(0x0048)(HasGetValueTypeHash)
	class FText                                   CallFunc_SelectText_ReturnValue;                   // 0x0088(0x0010)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0098(0x0048)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x00E0(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00F0(0x0010)()
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Convert_Modifier_to_Percent_Text;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Get Selected Shell Detection Modifier Color
// 0x0068 (0x0068 - 0x0000)
struct WBP_Loadout_Ammunition_C_Get_Selected_Shell_Detection_Modifier_Color final
{
public:
	struct FSlateColor                            Visibility_0;                                      // 0x0000(0x0014)(Parm, OutParm)
	struct FLinearColor                           Temp_struct_Variable;                              // 0x0014(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_1;                            // 0x0024(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0035(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0036(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37[0x1];                                       // 0x0037(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           K2Node_Select_Default;                             // 0x0038(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0048(0x0014)()
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast;      // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Get_Selected_Shell_Detection_Modifier_Color;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Get Selected Shell Detection Modifier Text
// 0x0030 (0x0030 - 0x0000)
struct WBP_Loadout_Ammunition_C_Get_Selected_Shell_Detection_Modifier_Text final
{
public:
	class FText                                   PercentText;                                       // 0x0000(0x0010)(Parm, OutParm)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Convert_Modifier_to_Percent_Text_Result;  // 0x0018(0x0010)()
	double                                        CallFunc_Convert_Modifier_to_Percent_Text_InModifier_ImplicitCast; // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Get_Selected_Shell_Detection_Modifier_Text;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Get Selected Shell Detection Modifier Visibility
// 0x0010 (0x0010 - 0x0000)
struct WBP_Loadout_Ammunition_C_Get_Selected_Shell_Detection_Modifier_Visibility final
{
public:
	ESlateVisibility                              Visibility_0;                                      // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_DoubleDouble_ReturnValue;      // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7[0x1];                                        // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast;   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Get_Selected_Shell_Detection_Modifier_Visibility;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Get Selected Shell Dispersion Modifier Color
// 0x0068 (0x0068 - 0x0000)
struct WBP_Loadout_Ammunition_C_Get_Selected_Shell_Dispersion_Modifier_Color final
{
public:
	struct FSlateColor                            Visibility_0;                                      // 0x0000(0x0014)(Parm, OutParm)
	struct FLinearColor                           Temp_struct_Variable;                              // 0x0014(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_1;                            // 0x0024(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0035(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0036(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37[0x1];                                       // 0x0037(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           K2Node_Select_Default;                             // 0x0038(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0048(0x0014)()
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast;      // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Get_Selected_Shell_Dispersion_Modifier_Color;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Get Selected Shell Dispersion Modifier Text
// 0x0030 (0x0030 - 0x0000)
struct WBP_Loadout_Ammunition_C_Get_Selected_Shell_Dispersion_Modifier_Text final
{
public:
	class FText                                   PercentText;                                       // 0x0000(0x0010)(Parm, OutParm)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Convert_Modifier_to_Percent_Text_Result;  // 0x0018(0x0010)()
	double                                        CallFunc_Convert_Modifier_to_Percent_Text_InModifier_ImplicitCast; // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Get_Selected_Shell_Dispersion_Modifier_Text;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Get Selected Shell Dispersion Modifier Visibility
// 0x0010 (0x0010 - 0x0000)
struct WBP_Loadout_Ammunition_C_Get_Selected_Shell_Dispersion_Modifier_Visibility final
{
public:
	ESlateVisibility                              Visibility_0;                                      // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_DoubleDouble_ReturnValue;      // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7[0x1];                                        // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast;   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Get_Selected_Shell_Dispersion_Modifier_Visibility;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Get Selected Shell Dmg Modifier Color
// 0x0068 (0x0068 - 0x0000)
struct WBP_Loadout_Ammunition_C_Get_Selected_Shell_Dmg_Modifier_Color final
{
public:
	struct FSlateColor                            Visibility_0;                                      // 0x0000(0x0014)(Parm, OutParm)
	struct FLinearColor                           Temp_struct_Variable;                              // 0x0014(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_1;                            // 0x0024(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0035(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0036(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37[0x1];                                       // 0x0037(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           K2Node_Select_Default;                             // 0x0038(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0048(0x0014)()
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast;      // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Get_Selected_Shell_Dmg_Modifier_Color;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Get Selected Shell Dmg Modifier Text
// 0x0030 (0x0030 - 0x0000)
struct WBP_Loadout_Ammunition_C_Get_Selected_Shell_Dmg_Modifier_Text final
{
public:
	class FText                                   NewParam;                                          // 0x0000(0x0010)(Parm, OutParm)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Convert_Modifier_to_Percent_Text_Result;  // 0x0018(0x0010)()
	double                                        CallFunc_Convert_Modifier_to_Percent_Text_InModifier_ImplicitCast; // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Get_Selected_Shell_Dmg_Modifier_Text;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Get Selected Shell Dmg Modifier Visibility
// 0x0010 (0x0010 - 0x0000)
struct WBP_Loadout_Ammunition_C_Get_Selected_Shell_Dmg_Modifier_Visibility final
{
public:
	ESlateVisibility                              Visibility_0;                                      // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_DoubleDouble_ReturnValue;      // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7[0x1];                                        // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast;   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Get_Selected_Shell_Dmg_Modifier_Visibility;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Get Selected Shell Pen Modifier Color
// 0x0068 (0x0068 - 0x0000)
struct WBP_Loadout_Ammunition_C_Get_Selected_Shell_Pen_Modifier_Color final
{
public:
	struct FSlateColor                            Visibility_0;                                      // 0x0000(0x0014)(Parm, OutParm)
	struct FLinearColor                           Temp_struct_Variable;                              // 0x0014(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_1;                            // 0x0024(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0035(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0036(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37[0x1];                                       // 0x0037(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           K2Node_Select_Default;                             // 0x0038(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0048(0x0014)()
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast;      // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Get_Selected_Shell_Pen_Modifier_Color;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Get Selected Shell Pen Modifier Text
// 0x0030 (0x0030 - 0x0000)
struct WBP_Loadout_Ammunition_C_Get_Selected_Shell_Pen_Modifier_Text final
{
public:
	class FText                                   PercentText;                                       // 0x0000(0x0010)(Parm, OutParm)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Convert_Modifier_to_Percent_Text_Result;  // 0x0018(0x0010)()
	double                                        CallFunc_Convert_Modifier_to_Percent_Text_InModifier_ImplicitCast; // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Get_Selected_Shell_Pen_Modifier_Text;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Get Selected Shell Pen Modifier Visibility
// 0x0010 (0x0010 - 0x0000)
struct WBP_Loadout_Ammunition_C_Get_Selected_Shell_Pen_Modifier_Visibility final
{
public:
	ESlateVisibility                              Visibility_0;                                      // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_DoubleDouble_ReturnValue;      // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7[0x1];                                        // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast;   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Get_Selected_Shell_Pen_Modifier_Visibility;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Get Selected Shell Reload Modifier Color
// 0x0068 (0x0068 - 0x0000)
struct WBP_Loadout_Ammunition_C_Get_Selected_Shell_Reload_Modifier_Color final
{
public:
	struct FSlateColor                            Visibility_0;                                      // 0x0000(0x0014)(Parm, OutParm)
	struct FLinearColor                           Temp_struct_Variable;                              // 0x0014(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_1;                            // 0x0024(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0035(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0036(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37[0x1];                                       // 0x0037(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           K2Node_Select_Default;                             // 0x0038(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0048(0x0014)()
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast;      // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Get_Selected_Shell_Reload_Modifier_Color;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Get Selected Shell Reload Modifier Text
// 0x0030 (0x0030 - 0x0000)
struct WBP_Loadout_Ammunition_C_Get_Selected_Shell_Reload_Modifier_Text final
{
public:
	class FText                                   PercentText;                                       // 0x0000(0x0010)(Parm, OutParm)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Convert_Modifier_to_Percent_Text_Result;  // 0x0018(0x0010)()
	double                                        CallFunc_Convert_Modifier_to_Percent_Text_InModifier_ImplicitCast; // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Get_Selected_Shell_Reload_Modifier_Text;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Get Selected Shell Reload Modifier Visibility
// 0x0010 (0x0010 - 0x0000)
struct WBP_Loadout_Ammunition_C_Get_Selected_Shell_Reload_Modifier_Visibility final
{
public:
	ESlateVisibility                              Visibility_0;                                      // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_DoubleDouble_ReturnValue;      // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7[0x1];                                        // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast;   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Get_Selected_Shell_Reload_Modifier_Visibility;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Get Selected Shell Velocity Modifier Color
// 0x0068 (0x0068 - 0x0000)
struct WBP_Loadout_Ammunition_C_Get_Selected_Shell_Velocity_Modifier_Color final
{
public:
	struct FSlateColor                            Visibility_0;                                      // 0x0000(0x0014)(Parm, OutParm)
	struct FLinearColor                           Temp_struct_Variable;                              // 0x0014(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_1;                            // 0x0024(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0035(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0036(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37[0x1];                                       // 0x0037(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           K2Node_Select_Default;                             // 0x0038(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0048(0x0014)()
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast;      // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Get_Selected_Shell_Velocity_Modifier_Color;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Get Selected Shell Velocity Modifier Text
// 0x0030 (0x0030 - 0x0000)
struct WBP_Loadout_Ammunition_C_Get_Selected_Shell_Velocity_Modifier_Text final
{
public:
	class FText                                   PercentText;                                       // 0x0000(0x0010)(Parm, OutParm)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Convert_Modifier_to_Percent_Text_Result;  // 0x0018(0x0010)()
	double                                        CallFunc_Convert_Modifier_to_Percent_Text_InModifier_ImplicitCast; // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Get_Selected_Shell_Velocity_Modifier_Text;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.Get Selected Shell Velocity Modifier Visibility
// 0x0010 (0x0010 - 0x0000)
struct WBP_Loadout_Ammunition_C_Get_Selected_Shell_Velocity_Modifier_Visibility final
{
public:
	ESlateVisibility                              Visibility_0;                                      // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_DoubleDouble_ReturnValue;      // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7[0x1];                                        // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast;   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_Get_Selected_Shell_Velocity_Modifier_Visibility;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.GetSelectedShellDescription
// 0x0018 (0x0018 - 0x0000)
struct WBP_Loadout_Ammunition_C_GetSelectedShellDescription final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_GetSelectedShellDescription;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.GetSelectedShellName
// 0x0018 (0x0018 - 0x0000)
struct WBP_Loadout_Ammunition_C_GetSelectedShellName final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_GetSelectedShellName;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.GetUnlockHeaderText
// 0x0028 (0x0028 - 0x0000)
struct WBP_Loadout_Ammunition_C_GetUnlockHeaderText final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm)
	class FText                                   CallFunc_GetCurrencyUnlockHeaderText_ReturnValue;  // 0x0010(0x0010)()
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_GetUnlockHeaderText;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.HasSelectedShell
// 0x0002 (0x0002 - 0x0000)
struct WBP_Loadout_Ammunition_C_HasSelectedShell final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_HasSelectedShell;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.ShowEquippedLabel
// 0x0007 (0x0007 - 0x0000)
struct WBP_Loadout_Ammunition_C_ShowEquippedLabel final
{
public:
	ESlateVisibility                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsEquipped_ReturnValue;                   // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_ShowEquippedLabel;

// Function WBP_Loadout_Ammunition.WBP_Loadout_Ammunition_C.ShowPurchaseUnlockLabel
// 0x0003 (0x0003 - 0x0000)
struct WBP_Loadout_Ammunition_C_ShowPurchaseUnlockLabel final
{
public:
	ESlateVisibility                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Loadout_Ammunition_C_ShowPurchaseUnlockLabel;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
