#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Loadout_TechTreeSlot

#include "Basic.hpp"

#include "WBP_Loadout_TechTreeSlot_classes.hpp"
#include "WBP_Loadout_TechTreeSlot_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Loadout_TechTreeSlot.WBP_Loadout_TechTreeSlot_C.SetVM_TechTree
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVM_TechTree_C*                   ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Loadout_TechTreeSlot_C::SetVM_TechTree(class UVM_TechTree_C* ViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTreeSlot_C", "SetVM_TechTree");

	Params::WBP_Loadout_TechTreeSlot_C_SetVM_TechTree Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Loadout_TechTreeSlot.WBP_Loadout_TechTreeSlot_C.__a33e7cc1-45af-073c-1077-eebb96ba4aeb_SourceToDest
// (Final, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FTyrMaterialTextureParam         ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FTyrMaterialTextureParam UWBP_Loadout_TechTreeSlot_C::__a33e7cc1_45af_073c_1077_eebb96ba4aeb_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTreeSlot_C", "__a33e7cc1-45af-073c-1077-eebb96ba4aeb_SourceToDest");

	Params::WBP_Loadout_TechTreeSlot_C___a33e7cc1_45af_073c_1077_eebb96ba4aeb_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
