#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HUD_LastStand

#include "Basic.hpp"

#include "WBP_HUD_LastStand_classes.hpp"
#include "WBP_HUD_LastStand_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_HUD_LastStand.WBP_HUD_LastStand_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_HUD_LastStand_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_LastStand_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HUD_LastStand.WBP_HUD_LastStand_C.ExecuteUbergraph_WBP_HUD_LastStand
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_LastStand_C::ExecuteUbergraph_WBP_HUD_LastStand(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_LastStand_C", "ExecuteUbergraph_WBP_HUD_LastStand");

	Params::WBP_HUD_LastStand_C_ExecuteUbergraph_WBP_HUD_LastStand Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_LastStand.WBP_HUD_LastStand_C.OnMessageReceived_A75856A248B3A159FBEA9DB4498310EB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAsyncAction_ListenForGameplayMessage*ProxyObject                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              ActualChannel                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_LastStand_C::OnMessageReceived_A75856A248B3A159FBEA9DB4498310EB(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_LastStand_C", "OnMessageReceived_A75856A248B3A159FBEA9DB4498310EB");

	Params::WBP_HUD_LastStand_C_OnMessageReceived_A75856A248B3A159FBEA9DB4498310EB Parms{};

	Parms.ProxyObject = ProxyObject;
	Parms.ActualChannel = std::move(ActualChannel);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_LastStand.WBP_HUD_LastStand_C.OnMessageReceived_E24ACB7240DBB647D5F6F6A5CC3E723B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAsyncAction_ListenForGameplayMessage*ProxyObject                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              ActualChannel                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_LastStand_C::OnMessageReceived_E24ACB7240DBB647D5F6F6A5CC3E723B(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_LastStand_C", "OnMessageReceived_E24ACB7240DBB647D5F6F6A5CC3E723B");

	Params::WBP_HUD_LastStand_C_OnMessageReceived_E24ACB7240DBB647D5F6F6A5CC3E723B Parms{};

	Parms.ProxyObject = ProxyObject;
	Parms.ActualChannel = std::move(ActualChannel);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
