#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Vehicle_Unlocked_Fallback

#include "Basic.hpp"

#include "WBP_Vehicle_Unlocked_Fallback_classes.hpp"
#include "WBP_Vehicle_Unlocked_Fallback_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Vehicle_Unlocked_Fallback.WBP_Vehicle_Unlocked_Fallback_C.BndEvt__WBP_Vehicle_Unlocked_Fallback_Button_Next_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Vehicle_Unlocked_Fallback_C::BndEvt__WBP_Vehicle_Unlocked_Fallback_Button_Next_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Vehicle_Unlocked_Fallback_C", "BndEvt__WBP_Vehicle_Unlocked_Fallback_Button_Next_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_Vehicle_Unlocked_Fallback_C_BndEvt__WBP_Vehicle_Unlocked_Fallback_Button_Next_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Vehicle_Unlocked_Fallback.WBP_Vehicle_Unlocked_Fallback_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UWBP_Vehicle_Unlocked_Fallback_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Vehicle_Unlocked_Fallback_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Vehicle_Unlocked_Fallback.WBP_Vehicle_Unlocked_Fallback_C.ExecuteUbergraph_WBP_Vehicle_Unlocked_Fallback
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Vehicle_Unlocked_Fallback_C::ExecuteUbergraph_WBP_Vehicle_Unlocked_Fallback(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Vehicle_Unlocked_Fallback_C", "ExecuteUbergraph_WBP_Vehicle_Unlocked_Fallback");

	Params::WBP_Vehicle_Unlocked_Fallback_C_ExecuteUbergraph_WBP_Vehicle_Unlocked_Fallback Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Vehicle_Unlocked_Fallback.WBP_Vehicle_Unlocked_Fallback_C.InitializeFromViewModel
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVM_Vehicle_Unlock_C*             InViewModel                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Vehicle_Unlocked_Fallback_C::InitializeFromViewModel(class UVM_Vehicle_Unlock_C* InViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Vehicle_Unlocked_Fallback_C", "InitializeFromViewModel");

	Params::WBP_Vehicle_Unlocked_Fallback_C_InitializeFromViewModel Parms{};

	Parms.InViewModel = InViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Vehicle_Unlocked_Fallback.WBP_Vehicle_Unlocked_Fallback_C.OnLoaded_D6E28221459F429D6360D28F4D56D738
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// TSubclassOf<class UObject>              Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

void UWBP_Vehicle_Unlocked_Fallback_C::OnLoaded_D6E28221459F429D6360D28F4D56D738(TSubclassOf<class UObject> Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Vehicle_Unlocked_Fallback_C", "OnLoaded_D6E28221459F429D6360D28F4D56D738");

	Params::WBP_Vehicle_Unlocked_Fallback_C_OnLoaded_D6E28221459F429D6360D28F4D56D738 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Vehicle_Unlocked_Fallback.WBP_Vehicle_Unlocked_Fallback_C.PreloadCinematicActor
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// TSoftClassPtr<class UClass>             VehicleCinematicActorClass                             (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UWBP_Vehicle_Unlocked_Fallback_C::PreloadCinematicActor(TSoftClassPtr<class UClass> VehicleCinematicActorClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Vehicle_Unlocked_Fallback_C", "PreloadCinematicActor");

	Params::WBP_Vehicle_Unlocked_Fallback_C_PreloadCinematicActor Parms{};

	Parms.VehicleCinematicActorClass = VehicleCinematicActorClass;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Vehicle_Unlocked_Fallback.WBP_Vehicle_Unlocked_Fallback_C.SetDismissButtonLabel
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      InButtonLabel                                          (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_Vehicle_Unlocked_Fallback_C::SetDismissButtonLabel(const class FText& InButtonLabel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Vehicle_Unlocked_Fallback_C", "SetDismissButtonLabel");

	Params::WBP_Vehicle_Unlocked_Fallback_C_SetDismissButtonLabel Parms{};

	Parms.InButtonLabel = std::move(InButtonLabel);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Vehicle_Unlocked_Fallback.WBP_Vehicle_Unlocked_Fallback_C.SetVM_Vehicle_Unlock
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVM_Vehicle_Unlock_C*             ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Vehicle_Unlocked_Fallback_C::SetVM_Vehicle_Unlock(class UVM_Vehicle_Unlock_C* ViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Vehicle_Unlocked_Fallback_C", "SetVM_Vehicle_Unlock");

	Params::WBP_Vehicle_Unlocked_Fallback_C_SetVM_Vehicle_Unlock Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Vehicle_Unlocked_Fallback.WBP_Vehicle_Unlocked_Fallback_C.__64287503-49bf-b6ea-4554-389614e1f0d5_SourceToDest
// (Final, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText*                            ClassText                                              (Parm, OutParm)

void UWBP_Vehicle_Unlocked_Fallback_C::__64287503_49bf_b6ea_4554_389614e1f0d5_SourceToDest(class FText* ClassText) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Vehicle_Unlocked_Fallback_C", "__64287503-49bf-b6ea-4554-389614e1f0d5_SourceToDest");

	Params::WBP_Vehicle_Unlocked_Fallback_C___64287503_49bf_b6ea_4554_389614e1f0d5_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ClassText != nullptr)
		*ClassText = std::move(Parms.ClassText);
}


// Function WBP_Vehicle_Unlocked_Fallback.WBP_Vehicle_Unlocked_Fallback_C.__99f5fe7a-4068-6e85-8ad8-73982000e053_SourceToDest
// (Final, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class UTexture2D**                      Icon                                                   (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Vehicle_Unlocked_Fallback_C::__99f5fe7a_4068_6e85_8ad8_73982000e053_SourceToDest(class UTexture2D** Icon) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Vehicle_Unlocked_Fallback_C", "__99f5fe7a-4068-6e85-8ad8-73982000e053_SourceToDest");

	Params::WBP_Vehicle_Unlocked_Fallback_C___99f5fe7a_4068_6e85_8ad8_73982000e053_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Icon != nullptr)
		*Icon = Parms.Icon;
}


// Function WBP_Vehicle_Unlocked_Fallback.WBP_Vehicle_Unlocked_Fallback_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_Vehicle_Unlocked_Fallback_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Vehicle_Unlocked_Fallback_C", "BP_GetDesiredFocusTarget");

	Params::WBP_Vehicle_Unlocked_Fallback_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
