#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Lobby_Spectator_Left

#include "Basic.hpp"

#include "WBP_Lobby_Spectator_Left_classes.hpp"
#include "WBP_Lobby_Spectator_Left_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Lobby_Spectator_Left.WBP_Lobby_Spectator_Left_C.BndEvt__WBP_Lobby_Spectator_Left_Btn_SpectateTeam_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Lobby_Spectator_Left_C::BndEvt__WBP_Lobby_Spectator_Left_Btn_SpectateTeam_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Spectator_Left_C", "BndEvt__WBP_Lobby_Spectator_Left_Btn_SpectateTeam_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_Lobby_Spectator_Left_C_BndEvt__WBP_Lobby_Spectator_Left_Btn_SpectateTeam_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Lobby_Spectator_Left.WBP_Lobby_Spectator_Left_C.BndEvt__WBP_Lobby_Spectator_Left_Btn_SpectateTeam_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Lobby_Spectator_Left_C::BndEvt__WBP_Lobby_Spectator_Left_Btn_SpectateTeam_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Spectator_Left_C", "BndEvt__WBP_Lobby_Spectator_Left_Btn_SpectateTeam_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_Lobby_Spectator_Left_C_BndEvt__WBP_Lobby_Spectator_Left_Btn_SpectateTeam_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Lobby_Spectator_Left.WBP_Lobby_Spectator_Left_C.BndEvt__WBP_Lobby_Spectator_Left_Btn_SpectateTeam_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Lobby_Spectator_Left_C::BndEvt__WBP_Lobby_Spectator_Left_Btn_SpectateTeam_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Spectator_Left_C", "BndEvt__WBP_Lobby_Spectator_Left_Btn_SpectateTeam_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_Lobby_Spectator_Left_C_BndEvt__WBP_Lobby_Spectator_Left_Btn_SpectateTeam_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Lobby_Spectator_Left.WBP_Lobby_Spectator_Left_C.BndEvt__WBP_Lobby_Spectator_Left_SpectatorDetails_MenuAnchor_K2Node_ComponentBoundEvent_1_OnShowContextMenu__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UTyrContextMenuWidget*            MenuWidget                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Lobby_Spectator_Left_C::BndEvt__WBP_Lobby_Spectator_Left_SpectatorDetails_MenuAnchor_K2Node_ComponentBoundEvent_1_OnShowContextMenu__DelegateSignature(class UTyrContextMenuWidget* MenuWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Spectator_Left_C", "BndEvt__WBP_Lobby_Spectator_Left_SpectatorDetails_MenuAnchor_K2Node_ComponentBoundEvent_1_OnShowContextMenu__DelegateSignature");

	Params::WBP_Lobby_Spectator_Left_C_BndEvt__WBP_Lobby_Spectator_Left_SpectatorDetails_MenuAnchor_K2Node_ComponentBoundEvent_1_OnShowContextMenu__DelegateSignature Parms{};

	Parms.MenuWidget = MenuWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Lobby_Spectator_Left.WBP_Lobby_Spectator_Left_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UWBP_Lobby_Spectator_Left_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Spectator_Left_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Lobby_Spectator_Left.WBP_Lobby_Spectator_Left_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Lobby_Spectator_Left_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Spectator_Left_C", "BP_OnItemExpansionChanged");

	Params::WBP_Lobby_Spectator_Left_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Lobby_Spectator_Left.WBP_Lobby_Spectator_Left_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Lobby_Spectator_Left_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Spectator_Left_C", "BP_OnItemSelectionChanged");

	Params::WBP_Lobby_Spectator_Left_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Lobby_Spectator_Left.WBP_Lobby_Spectator_Left_C.ExecuteUbergraph_WBP_Lobby_Spectator_Left
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Lobby_Spectator_Left_C::ExecuteUbergraph_WBP_Lobby_Spectator_Left(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Spectator_Left_C", "ExecuteUbergraph_WBP_Lobby_Spectator_Left");

	Params::WBP_Lobby_Spectator_Left_C_ExecuteUbergraph_WBP_Lobby_Spectator_Left Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Lobby_Spectator_Left.WBP_Lobby_Spectator_Left_C.OnAddedToFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_Lobby_Spectator_Left_C::OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Spectator_Left_C", "OnAddedToFocusPath");

	Params::WBP_Lobby_Spectator_Left_C_OnAddedToFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Lobby_Spectator_Left.WBP_Lobby_Spectator_Left_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_Lobby_Spectator_Left_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Spectator_Left_C", "OnFocusReceived");

	Params::WBP_Lobby_Spectator_Left_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Lobby_Spectator_Left.WBP_Lobby_Spectator_Left_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Lobby_Spectator_Left_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Spectator_Left_C", "OnListItemObjectSet");

	Params::WBP_Lobby_Spectator_Left_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Lobby_Spectator_Left.WBP_Lobby_Spectator_Left_C.OnRemovedFromFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_Lobby_Spectator_Left_C::OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Spectator_Left_C", "OnRemovedFromFocusPath");

	Params::WBP_Lobby_Spectator_Left_C_OnRemovedFromFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Lobby_Spectator_Left.WBP_Lobby_Spectator_Left_C.SetVM_Lobby_Player
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVM_Lobby_Player_C*               ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Lobby_Spectator_Left_C::SetVM_Lobby_Player(class UVM_Lobby_Player_C* ViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Spectator_Left_C", "SetVM_Lobby_Player");

	Params::WBP_Lobby_Spectator_Left_C_SetVM_Lobby_Player Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Lobby_Spectator_Left.WBP_Lobby_Spectator_Left_C.__6802c73d-42d4-7db1-9d73-62af3ab30495_SourceToDest
// (Final, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_Lobby_Spectator_Left_C::__6802c73d_42d4_7db1_9d73_62af3ab30495_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Spectator_Left_C", "__6802c73d-42d4-7db1-9d73-62af3ab30495_SourceToDest");

	Params::WBP_Lobby_Spectator_Left_C___6802c73d_42d4_7db1_9d73_62af3ab30495_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Lobby_Spectator_Left.WBP_Lobby_Spectator_Left_C.__6d085b5b-49f1-a562-25df-2286e1895c96_SourceToDest
// (Final, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_Lobby_Spectator_Left_C::__6d085b5b_49f1_a562_25df_2286e1895c96_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Spectator_Left_C", "__6d085b5b-49f1-a562-25df-2286e1895c96_SourceToDest");

	Params::WBP_Lobby_Spectator_Left_C___6d085b5b_49f1_a562_25df_2286e1895c96_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Lobby_Spectator_Left.WBP_Lobby_Spectator_Left_C.__7fe5cf4d-46ec-d348-5e96-45aa4a1ffa0d_SourceToDest
// (Final, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_Lobby_Spectator_Left_C::__7fe5cf4d_46ec_d348_5e96_45aa4a1ffa0d_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Spectator_Left_C", "__7fe5cf4d-46ec-d348-5e96-45aa4a1ffa0d_SourceToDest");

	Params::WBP_Lobby_Spectator_Left_C___7fe5cf4d_46ec_d348_5e96_45aa4a1ffa0d_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Lobby_Spectator_Left.WBP_Lobby_Spectator_Left_C.__c1d5a0f0-40f8-ba31-8cdc-269a493b8a26_SourceToDest
// (Final, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UWBP_Lobby_Spectator_Left_C::__c1d5a0f0_40f8_ba31_8cdc_269a493b8a26_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Spectator_Left_C", "__c1d5a0f0-40f8-ba31-8cdc-269a493b8a26_SourceToDest");

	Params::WBP_Lobby_Spectator_Left_C___c1d5a0f0_40f8_ba31_8cdc_269a493b8a26_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
