#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Cosmetics_Charm_List

#include "Basic.hpp"

#include "WBP_Cosmetics_Charm_List_classes.hpp"
#include "WBP_Cosmetics_Charm_List_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Cosmetics_Charm_List.WBP_Cosmetics_Charm_List_C.BndEvt__WBP_Cosmetics_Charm_List_Charms_TileView_K2Node_ComponentBoundEvent_2_SimpleListItemEventDynamic__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Cosmetics_Charm_List_C::BndEvt__WBP_Cosmetics_Charm_List_Charms_TileView_K2Node_ComponentBoundEvent_2_SimpleListItemEventDynamic__DelegateSignature(class UObject* Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Cosmetics_Charm_List_C", "BndEvt__WBP_Cosmetics_Charm_List_Charms_TileView_K2Node_ComponentBoundEvent_2_SimpleListItemEventDynamic__DelegateSignature");

	Params::WBP_Cosmetics_Charm_List_C_BndEvt__WBP_Cosmetics_Charm_List_Charms_TileView_K2Node_ComponentBoundEvent_2_SimpleListItemEventDynamic__DelegateSignature Parms{};

	Parms.Item = Item;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Cosmetics_Charm_List.WBP_Cosmetics_Charm_List_C.BndEvt__WBP_Cosmetics_Charm_List_WBP_Button_Text_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Cosmetics_Charm_List_C::BndEvt__WBP_Cosmetics_Charm_List_WBP_Button_Text_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Cosmetics_Charm_List_C", "BndEvt__WBP_Cosmetics_Charm_List_WBP_Button_Text_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_Cosmetics_Charm_List_C_BndEvt__WBP_Cosmetics_Charm_List_WBP_Button_Text_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Cosmetics_Charm_List.WBP_Cosmetics_Charm_List_C.ExecuteUbergraph_WBP_Cosmetics_Charm_List
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Cosmetics_Charm_List_C::ExecuteUbergraph_WBP_Cosmetics_Charm_List(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Cosmetics_Charm_List_C", "ExecuteUbergraph_WBP_Cosmetics_Charm_List");

	Params::WBP_Cosmetics_Charm_List_C_ExecuteUbergraph_WBP_Cosmetics_Charm_List Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Cosmetics_Charm_List.WBP_Cosmetics_Charm_List_C.InputAction_DT_Settings_SaveActions_SaveClose_Clicked
// (BlueprintEvent)

void UWBP_Cosmetics_Charm_List_C::InputAction_DT_Settings_SaveActions_SaveClose_Clicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Cosmetics_Charm_List_C", "InputAction_DT_Settings_SaveActions_SaveClose_Clicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Cosmetics_Charm_List.WBP_Cosmetics_Charm_List_C.SaveAndOrClose
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Cosmetics_Charm_List_C::SaveAndOrClose()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Cosmetics_Charm_List_C", "SaveAndOrClose");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Cosmetics_Charm_List.WBP_Cosmetics_Charm_List_C.SetVM_Cosmetics_Vehicle
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVM_Cosmetics_Vehicle_C*          ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Cosmetics_Charm_List_C::SetVM_Cosmetics_Vehicle(class UVM_Cosmetics_Vehicle_C* ViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Cosmetics_Charm_List_C", "SetVM_Cosmetics_Vehicle");

	Params::WBP_Cosmetics_Charm_List_C_SetVM_Cosmetics_Vehicle Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Cosmetics_Charm_List.WBP_Cosmetics_Charm_List_C.UpdateConfirmStyleVisibility
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Cosmetics_Charm_List_C::UpdateConfirmStyleVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Cosmetics_Charm_List_C", "UpdateConfirmStyleVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Cosmetics_Charm_List.WBP_Cosmetics_Charm_List_C.__18b29822-4c3c-fd8f-2ff8-828b08ad1fa5_SourceToDest
// (Final, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_Cosmetics_Charm_List_C::__18b29822_4c3c_fd8f_2ff8_828b08ad1fa5_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Cosmetics_Charm_List_C", "__18b29822-4c3c-fd8f-2ff8-828b08ad1fa5_SourceToDest");

	Params::WBP_Cosmetics_Charm_List_C___18b29822_4c3c_fd8f_2ff8_828b08ad1fa5_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Cosmetics_Charm_List.WBP_Cosmetics_Charm_List_C.__aa4c0a8c-4255-4d0b-30b3-9cbee0cb85a0_SourceToDest
// (Final, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// double                                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

double UWBP_Cosmetics_Charm_List_C::__aa4c0a8c_4255_4d0b_30b3_9cbee0cb85a0_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Cosmetics_Charm_List_C", "__aa4c0a8c-4255-4d0b-30b3-9cbee0cb85a0_SourceToDest");

	Params::WBP_Cosmetics_Charm_List_C___aa4c0a8c_4255_4d0b_30b3_9cbee0cb85a0_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Cosmetics_Charm_List.WBP_Cosmetics_Charm_List_C.__ConversionFunction0717c59e-7e31-3026-8477-491540b3dbe2
// (Final, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_Cosmetics_Charm_List_C::__ConversionFunction0717c59e_7e31_3026_8477_491540b3dbe2() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Cosmetics_Charm_List_C", "__ConversionFunction0717c59e-7e31-3026-8477-491540b3dbe2");

	Params::WBP_Cosmetics_Charm_List_C___ConversionFunction0717c59e_7e31_3026_8477_491540b3dbe2 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Cosmetics_Charm_List.WBP_Cosmetics_Charm_List_C.__defc4b01-4062-27d2-140c-c69b88491e09_SourceToDest
// (Final, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_Cosmetics_Charm_List_C::__defc4b01_4062_27d2_140c_c69b88491e09_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Cosmetics_Charm_List_C", "__defc4b01-4062-27d2-140c-c69b88491e09_SourceToDest");

	Params::WBP_Cosmetics_Charm_List_C___defc4b01_4062_27d2_140c_c69b88491e09_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Cosmetics_Charm_List.WBP_Cosmetics_Charm_List_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_Cosmetics_Charm_List_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Cosmetics_Charm_List_C", "BP_GetDesiredFocusTarget");

	Params::WBP_Cosmetics_Charm_List_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
