#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RegionSelect

#include "Basic.hpp"

#include "WBP_RegionSelect_classes.hpp"
#include "WBP_RegionSelect_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_RegionSelect.WBP_RegionSelect_C.BndEvt__WBP_RegionSelect_WBP_Asia_K2Node_ComponentBoundEvent_5_OnRegionSelected__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FString&                    RegionId                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_RegionSelect_C::BndEvt__WBP_RegionSelect_WBP_Asia_K2Node_ComponentBoundEvent_5_OnRegionSelected__DelegateSignature(const class FString& RegionId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RegionSelect_C", "BndEvt__WBP_RegionSelect_WBP_Asia_K2Node_ComponentBoundEvent_5_OnRegionSelected__DelegateSignature");

	Params::WBP_RegionSelect_C_BndEvt__WBP_RegionSelect_WBP_Asia_K2Node_ComponentBoundEvent_5_OnRegionSelected__DelegateSignature Parms{};

	Parms.RegionId = std::move(RegionId);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RegionSelect.WBP_RegionSelect_C.BndEvt__WBP_RegionSelect_WBP_EU_K2Node_ComponentBoundEvent_4_OnRegionSelected__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FString&                    RegionId                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_RegionSelect_C::BndEvt__WBP_RegionSelect_WBP_EU_K2Node_ComponentBoundEvent_4_OnRegionSelected__DelegateSignature(const class FString& RegionId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RegionSelect_C", "BndEvt__WBP_RegionSelect_WBP_EU_K2Node_ComponentBoundEvent_4_OnRegionSelected__DelegateSignature");

	Params::WBP_RegionSelect_C_BndEvt__WBP_RegionSelect_WBP_EU_K2Node_ComponentBoundEvent_4_OnRegionSelected__DelegateSignature Parms{};

	Parms.RegionId = std::move(RegionId);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RegionSelect.WBP_RegionSelect_C.BndEvt__WBP_RegionSelect_WBP_NAEast_K2Node_ComponentBoundEvent_3_OnRegionSelected__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FString&                    RegionId                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_RegionSelect_C::BndEvt__WBP_RegionSelect_WBP_NAEast_K2Node_ComponentBoundEvent_3_OnRegionSelected__DelegateSignature(const class FString& RegionId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RegionSelect_C", "BndEvt__WBP_RegionSelect_WBP_NAEast_K2Node_ComponentBoundEvent_3_OnRegionSelected__DelegateSignature");

	Params::WBP_RegionSelect_C_BndEvt__WBP_RegionSelect_WBP_NAEast_K2Node_ComponentBoundEvent_3_OnRegionSelected__DelegateSignature Parms{};

	Parms.RegionId = std::move(RegionId);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RegionSelect.WBP_RegionSelect_C.BndEvt__WBP_RegionSelect_WBP_NAWest_K2Node_ComponentBoundEvent_2_OnRegionSelected__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FString&                    RegionId                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_RegionSelect_C::BndEvt__WBP_RegionSelect_WBP_NAWest_K2Node_ComponentBoundEvent_2_OnRegionSelected__DelegateSignature(const class FString& RegionId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RegionSelect_C", "BndEvt__WBP_RegionSelect_WBP_NAWest_K2Node_ComponentBoundEvent_2_OnRegionSelected__DelegateSignature");

	Params::WBP_RegionSelect_C_BndEvt__WBP_RegionSelect_WBP_NAWest_K2Node_ComponentBoundEvent_2_OnRegionSelected__DelegateSignature Parms{};

	Parms.RegionId = std::move(RegionId);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RegionSelect.WBP_RegionSelect_C.BndEvt__WBP_RegionSelect_WBP_SouthAmerica_K2Node_ComponentBoundEvent_1_OnRegionSelected__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FString&                    RegionId                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_RegionSelect_C::BndEvt__WBP_RegionSelect_WBP_SouthAmerica_K2Node_ComponentBoundEvent_1_OnRegionSelected__DelegateSignature(const class FString& RegionId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RegionSelect_C", "BndEvt__WBP_RegionSelect_WBP_SouthAmerica_K2Node_ComponentBoundEvent_1_OnRegionSelected__DelegateSignature");

	Params::WBP_RegionSelect_C_BndEvt__WBP_RegionSelect_WBP_SouthAmerica_K2Node_ComponentBoundEvent_1_OnRegionSelected__DelegateSignature Parms{};

	Parms.RegionId = std::move(RegionId);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RegionSelect.WBP_RegionSelect_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UWBP_RegionSelect_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RegionSelect_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_RegionSelect.WBP_RegionSelect_C.ExecuteUbergraph_WBP_RegionSelect
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RegionSelect_C::ExecuteUbergraph_WBP_RegionSelect(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RegionSelect_C", "ExecuteUbergraph_WBP_RegionSelect");

	Params::WBP_RegionSelect_C_ExecuteUbergraph_WBP_RegionSelect Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RegionSelect.WBP_RegionSelect_C.InputAction_DT_UniversalAction_GenericAccept_Clicked
// (BlueprintEvent)

void UWBP_RegionSelect_C::InputAction_DT_UniversalAction_GenericAccept_Clicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RegionSelect_C", "InputAction_DT_UniversalAction_GenericAccept_Clicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_RegionSelect.WBP_RegionSelect_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_RegionSelect_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RegionSelect_C", "BP_GetDesiredFocusTarget");

	Params::WBP_RegionSelect_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
