#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Loadout_TechTree_Node

#include "Basic.hpp"

#include "WBP_Loadout_TechTree_Node_classes.hpp"
#include "WBP_Loadout_TechTree_Node_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Loadout_TechTree_Node.WBP_Loadout_TechTree_Node_C.BP_OnClicked
// (Event, Protected, BlueprintEvent)

void UWBP_Loadout_TechTree_Node_C::BP_OnClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTree_Node_C", "BP_OnClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Loadout_TechTree_Node.WBP_Loadout_TechTree_Node_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UWBP_Loadout_TechTree_Node_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTree_Node_C", "BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Loadout_TechTree_Node.WBP_Loadout_TechTree_Node_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UWBP_Loadout_TechTree_Node_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTree_Node_C", "BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Loadout_TechTree_Node.WBP_Loadout_TechTree_Node_C.ExecuteUbergraph_WBP_Loadout_TechTree_Node
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Loadout_TechTree_Node_C::ExecuteUbergraph_WBP_Loadout_TechTree_Node(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTree_Node_C", "ExecuteUbergraph_WBP_Loadout_TechTree_Node");

	Params::WBP_Loadout_TechTree_Node_C_ExecuteUbergraph_WBP_Loadout_TechTree_Node Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Loadout_TechTree_Node.WBP_Loadout_TechTree_Node_C.OnKeyUp
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FKeyEvent&                 InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_Loadout_TechTree_Node_C::OnKeyUp(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTree_Node_C", "OnKeyUp");

	Params::WBP_Loadout_TechTree_Node_C_OnKeyUp Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Loadout_TechTree_Node.WBP_Loadout_TechTree_Node_C.OnMouseButtonUp
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_Loadout_TechTree_Node_C::OnMouseButtonUp(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTree_Node_C", "OnMouseButtonUp");

	Params::WBP_Loadout_TechTree_Node_C_OnMouseButtonUp Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Loadout_TechTree_Node.WBP_Loadout_TechTree_Node_C.SetupTalentNode
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVM_TechTree_Node_C*              InNodeViewModel                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const TDelegate<void(class UVM_TechTree_Node_C* Node)>&InNodeFocusedDelegate                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UWBP_Loadout_TechTree_Node_C::SetupTalentNode(class UVM_TechTree_Node_C* InNodeViewModel, const TDelegate<void(class UVM_TechTree_Node_C* Node)>& InNodeFocusedDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTree_Node_C", "SetupTalentNode");

	Params::WBP_Loadout_TechTree_Node_C_SetupTalentNode Parms{};

	Parms.InNodeViewModel = InNodeViewModel;
	Parms.InNodeFocusedDelegate = InNodeFocusedDelegate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Loadout_TechTree_Node.WBP_Loadout_TechTree_Node_C.SetVM_TechTree_Node
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVM_TechTree_Node_C*              ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Loadout_TechTree_Node_C::SetVM_TechTree_Node(class UVM_TechTree_Node_C* ViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTree_Node_C", "SetVM_TechTree_Node");

	Params::WBP_Loadout_TechTree_Node_C_SetVM_TechTree_Node Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Loadout_TechTree_Node.WBP_Loadout_TechTree_Node_C.TryAddPoint
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Loadout_TechTree_Node_C::TryAddPoint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTree_Node_C", "TryAddPoint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Loadout_TechTree_Node.WBP_Loadout_TechTree_Node_C.TryRemovePoint
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Loadout_TechTree_Node_C::TryRemovePoint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTree_Node_C", "TryRemovePoint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Loadout_TechTree_Node.WBP_Loadout_TechTree_Node_C.__08eb53de-4bda-d1a7-30a5-ff9e60765363_SourceToDest
// (Final, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UWBP_Loadout_TechTree_Node_C::__08eb53de_4bda_d1a7_30a5_ff9e60765363_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTree_Node_C", "__08eb53de-4bda-d1a7-30a5-ff9e60765363_SourceToDest");

	Params::WBP_Loadout_TechTree_Node_C___08eb53de_4bda_d1a7_30a5_ff9e60765363_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Loadout_TechTree_Node.WBP_Loadout_TechTree_Node_C.__09e229d6-4134-df7e-be23-4e9be8ba1915_SourceToDest
// (Final, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_Loadout_TechTree_Node_C::__09e229d6_4134_df7e_be23_4e9be8ba1915_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTree_Node_C", "__09e229d6-4134-df7e-be23-4e9be8ba1915_SourceToDest");

	Params::WBP_Loadout_TechTree_Node_C___09e229d6_4134_df7e_be23_4e9be8ba1915_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Loadout_TechTree_Node.WBP_Loadout_TechTree_Node_C.__5666077b-4d0e-3e8f-d1e1-69a08825628e_SourceToDest
// (Final, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FTyrMaterialTextureParam         ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FTyrMaterialTextureParam UWBP_Loadout_TechTree_Node_C::__5666077b_4d0e_3e8f_d1e1_69a08825628e_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTree_Node_C", "__5666077b-4d0e-3e8f-d1e1-69a08825628e_SourceToDest");

	Params::WBP_Loadout_TechTree_Node_C___5666077b_4d0e_3e8f_d1e1_69a08825628e_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Loadout_TechTree_Node.WBP_Loadout_TechTree_Node_C.__7238e57e-453a-644a-cf26-529c0d16efea_SourceToDest
// (Final, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FTyrMaterialScalarParam          ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor)

struct FTyrMaterialScalarParam UWBP_Loadout_TechTree_Node_C::__7238e57e_453a_644a_cf26_529c0d16efea_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTree_Node_C", "__7238e57e-453a-644a-cf26-529c0d16efea_SourceToDest");

	Params::WBP_Loadout_TechTree_Node_C___7238e57e_453a_644a_cf26_529c0d16efea_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Loadout_TechTree_Node.WBP_Loadout_TechTree_Node_C.__93a1be49-4d22-8dbf-18c0-b9bb0d558b64_SourceToDest
// (Final, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_Loadout_TechTree_Node_C::__93a1be49_4d22_8dbf_18c0_b9bb0d558b64_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTree_Node_C", "__93a1be49-4d22-8dbf-18c0-b9bb0d558b64_SourceToDest");

	Params::WBP_Loadout_TechTree_Node_C___93a1be49_4d22_8dbf_18c0_b9bb0d558b64_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Loadout_TechTree_Node.WBP_Loadout_TechTree_Node_C.__99c47ba6-40e8-17fa-c942-b88c4c655967_SourceToDest
// (Final, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_Loadout_TechTree_Node_C::__99c47ba6_40e8_17fa_c942_b88c4c655967_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTree_Node_C", "__99c47ba6-40e8-17fa-c942-b88c4c655967_SourceToDest");

	Params::WBP_Loadout_TechTree_Node_C___99c47ba6_40e8_17fa_c942_b88c4c655967_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Loadout_TechTree_Node.WBP_Loadout_TechTree_Node_C.__f32494cb-4b87-2a6c-92c5-72b7a021b974_SourceToDest
// (Final, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_Loadout_TechTree_Node_C::__f32494cb_4b87_2a6c_92c5_72b7a021b974_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTree_Node_C", "__f32494cb-4b87-2a6c-92c5-72b7a021b974_SourceToDest");

	Params::WBP_Loadout_TechTree_Node_C___f32494cb_4b87_2a6c_92c5_72b7a021b974_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Loadout_TechTree_Node.WBP_Loadout_TechTree_Node_C.__fc7b476f-4a89-5423-0f8e-61ac3fd6441e_SourceToDest
// (Final, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_Loadout_TechTree_Node_C::__fc7b476f_4a89_5423_0f8e_61ac3fd6441e_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Loadout_TechTree_Node_C", "__fc7b476f-4a89-5423-0f8e-61ac3fd6441e_SourceToDest");

	Params::WBP_Loadout_TechTree_Node_C___fc7b476f_4a89_5423_0f8e_61ac3fd6441e_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
