#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Lobby_Map_Entry

#include "Basic.hpp"

#include "WBP_Lobby_Map_Entry_classes.hpp"
#include "WBP_Lobby_Map_Entry_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Lobby_Map_Entry.WBP_Lobby_Map_Entry_C.BP_OnDeselected
// (Event, Protected, BlueprintEvent)

void UWBP_Lobby_Map_Entry_C::BP_OnDeselected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Map_Entry_C", "BP_OnDeselected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Lobby_Map_Entry.WBP_Lobby_Map_Entry_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UWBP_Lobby_Map_Entry_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Map_Entry_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Lobby_Map_Entry.WBP_Lobby_Map_Entry_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Lobby_Map_Entry_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Map_Entry_C", "BP_OnItemExpansionChanged");

	Params::WBP_Lobby_Map_Entry_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Lobby_Map_Entry.WBP_Lobby_Map_Entry_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Lobby_Map_Entry_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Map_Entry_C", "BP_OnItemSelectionChanged");

	Params::WBP_Lobby_Map_Entry_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Lobby_Map_Entry.WBP_Lobby_Map_Entry_C.BP_OnSelected
// (Event, Protected, BlueprintEvent)

void UWBP_Lobby_Map_Entry_C::BP_OnSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Map_Entry_C", "BP_OnSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Lobby_Map_Entry.WBP_Lobby_Map_Entry_C.ExecuteUbergraph_WBP_Lobby_Map_Entry
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Lobby_Map_Entry_C::ExecuteUbergraph_WBP_Lobby_Map_Entry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Map_Entry_C", "ExecuteUbergraph_WBP_Lobby_Map_Entry");

	Params::WBP_Lobby_Map_Entry_C_ExecuteUbergraph_WBP_Lobby_Map_Entry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Lobby_Map_Entry.WBP_Lobby_Map_Entry_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Lobby_Map_Entry_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Map_Entry_C", "OnListItemObjectSet");

	Params::WBP_Lobby_Map_Entry_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Lobby_Map_Entry.WBP_Lobby_Map_Entry_C.SetVM_Lobby_Map
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVM_Lobby_Map_C*                  ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Lobby_Map_Entry_C::SetVM_Lobby_Map(class UVM_Lobby_Map_C* ViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Lobby_Map_Entry_C", "SetVM_Lobby_Map");

	Params::WBP_Lobby_Map_Entry_C_SetVM_Lobby_Map Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
